#!/usr/bin/env python3
"""Build control-matrix.md from the published negative-control results.

Stdlib only. Reads the control definitions from negative_controls.py (the
exact mutations), the two I2-R1 runs (pre-commit/summary.json and
candidate-45898e05/summary.json) and the original I2A run
(../../original-i2a/i2a-negative-controls/summary.json), checks that the
30 retained controls are textually identical to I2A's, and writes the
matrix to standard output. Run from i2-r1/controls.
"""
import importlib.util
import json
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def controls(module):
    return module.CODEC + module.RETAINED + module.R2 + [module.SPLIT] + getattr(module, "NEW", [])


KEYS = ("id", "file", "target", "test", "marker", "anchor", "replacement", "require", "forbid")


def text(control):
    return {key: control.get(key) for key in KEYS}


def main():
    sys.dont_write_bytecode = True
    current = load("negative_controls", HERE / "negative_controls.py")
    as_run = load("as_run", HERE / "pre-commit" / "i2r1-negative-controls.py")
    i2a = load("i2a", HERE.parent.parent / "original-i2a" / "i2a-negative-controls.py")
    runs = {
        "pre-commit": json.loads((HERE / "pre-commit" / "summary.json").read_text()),
        "candidate": json.loads((HERE / "candidate-45898e05" / "summary.json").read_text()),
        "i2a": json.loads(
            (HERE.parent.parent / "original-i2a" / "i2a-negative-controls" / "summary.json").read_text()
        ),
    }
    defined = controls(current)
    same_as_run = [text(c) for c in defined] == [text(c) for c in controls(as_run)]
    i2a_defined = {c["id"]: text(c) for c in controls(i2a)}
    retained = [c for c in defined if not c["id"].startswith("NC-REQUEST")]
    retained_same = all(i2a_defined.get(c["id"]) == text(c) for c in retained)
    by_id = {name: {r["id"]: r for r in run["counted"]} for name, run in runs.items()}

    out = []
    w = out.append
    w("# P2-V1-R3B-I2-R1 negative-control matrix")
    w("")
    w("Generated by `control_matrix.py` from the published `summary.json` files and the")
    w("control definitions in `negative_controls.py`.")
    w("")
    w(f"- Counted controls defined: {len(defined)} "
      f"({len(retained)} retained from I2A, {len(defined) - len(retained)} new).")
    w(f"- Definitions identical to the as-run pre-commit script: {same_as_run}.")
    w(f"- The {len(retained)} retained definitions (id, file, target, test, marker, anchor, "
      f"replacement, required and forbidden traces) are identical to I2A's: {retained_same}.")
    w("- Pass condition for every counted control: the mutation's anchor occurs exactly once; the")
    w("  mutated sources compile; the intended test, run alone with `--exact`, fails with")
    w("  `test result: FAILED. 0 passed; 1 failed` and a nonzero exit; the marker is inside the")
    w("  failing assertion's message; any required trace is present and no forbidden one; and")
    w("  after the always-performed restoration all six envelope files have their original")
    w("  SHA-256 and the worktree status is exactly the expected one.")
    w("")
    w("## Counted controls")
    w("")
    w("Columns per run: exit status / compiled / failed the intended test / marker in the "
      "assertion / files restored. `I2A` is the original I2A run on 0eb2a947 (no NC-REQUEST rows).")
    w("")
    w("| # | Control | Mutated file | Test target | Intended test | Marker | Pre-commit run | "
      "Candidate 45898e05 run | I2A run |")
    w("|---|---|---|---|---|---|---|---|---|")

    def cell(result):
        if result is None:
            return "not in run"
        flags = [result["compiled"], result["failed_intended_test"],
                 result["marker_in_assertion"], result["files_restored"]]
        return f"{result['exit']} / " + " / ".join("yes" if f else "NO" for f in flags)

    all_ok = True
    for index, control in enumerate(defined, 1):
        cid = control["id"]
        pre, cand, old = (by_id[name].get(cid) for name in ("pre-commit", "candidate", "i2a"))
        for result in (pre, cand):
            ok = (result is not None and result["exit"] != 0 and result["compiled"]
                  and result["failed_intended_test"] and result["marker_in_assertion"]
                  and result["required_trace"] and not result["forbidden_trace"]
                  and result["files_restored"])
            all_ok &= ok
        w(f"| {index} | {cid} | `{control['file'].rsplit('/', 1)[-1]}` | {control['target']} | "
          f"`{control['test'].rsplit('::', 1)[-1]}` | `{control['marker']}` | {cell(pre)} | "
          f"{cell(cand)} | {cell(old)} |")
    w("")
    w(f"All {len(defined)} counted controls met every condition in both I2-R1 runs: {all_ok}.")
    w("")
    w("## Informational runs (not counted)")
    w("")
    w("What the older request checks see under the two new mutations. A c16 failure is a")
    w("source-guard failure and is not counted for either new control.")
    w("")
    w("| Run | Mutation | Test | Expected | Pre-commit | Candidate 45898e05 |")
    w("|---|---|---|---|---|---|")
    pre_info = {r["id"]: r for r in runs["pre-commit"]["informational"]}
    cand_info = {r["id"]: r for r in runs["candidate"]["informational"]}

    def outcome(result):
        if result is None:
            return "not in run"
        state = "passed" if result["passed"] else "failed" if result["failed"] else "neither"
        return f"{state} (exit {result['exit']}, restored {'yes' if result['files_restored'] else 'NO'})"

    for rid in pre_info:
        mutation = rid.rsplit("-", 1)[0]
        test = pre_info[rid]["test"]
        w(f"| {rid} | {mutation} | `{test}` | {pre_info[rid]['expect']} | "
          f"{outcome(pre_info[rid])} | {outcome(cand_info.get(rid))} |")
    structural = runs["i2a"].get("structural", [])
    if structural:
        w("")
        w("The original I2A run recorded the same Debug request mutation as structural only:")
        w("")
        w("| I2A run | Test | Result |")
        w("|---|---|---|")
        for result in structural:
            state = "passed" if result["passed"] else "failed" if result["failed"] else "neither"
            w(f"| {result['id']} | `{result['test']}` | {state} (exit {result['exit']}) |")
    w("")
    w("## Restoration evidence (SHA-256 of the six envelope files)")
    w("")
    for name, label in (("pre-commit", "Pre-commit run (sources byte-identical to the commit)"),
                        ("candidate", "Candidate run (clean checkout of 45898e05)"),
                        ("i2a", "Original I2A run (sources of 0eb2a947)")):
        summary = runs[name]["summary"]
        w(f"### {label}")
        w("")
        w(f"Counted {summary['counted']}, all required: {summary['counted_all_required']}, "
          f"final state identical to original: {summary['identical']}.")
        w("")
        w("| File | Before the controls | After the last restoration |")
        w("|---|---|---|")
        for path, digest in summary["original"].items():
            w(f"| `{path.split('nexus-verifier-sandbox/', 1)[-1]}` | `{digest}` | "
              f"`{summary['final'][path]}` |")
        w("")
    w("Each control's own entry also records `files_restored`, the check of all six files")
    w("against these values immediately after that control's restoration.")
    w("")
    w("## Exact mutations")
    w("")
    w("Each mutation replaces its anchor, which occurs exactly once in the mutated file, with "
      "the replacement; an empty replacement deletes the anchor.")
    for control in defined:
        w("")
        w(f"### {control['id']}: {control['what']}")
        w("")
        w(f"File `{control['file']}`; test `{control['test']}` in `{control['target']}`; "
          f"marker `{control['marker']}`.")
        if control.get("require"):
            w(f"Required in the assertion: {control['require']}.")
        if control.get("forbid"):
            w(f"Forbidden in the assertion: {control['forbid']}.")
        w("")
        w("```diff")
        for line in control["anchor"].rstrip("\n").split("\n"):
            w(f"-{line}")
        if control["replacement"]:
            for line in control["replacement"].rstrip("\n").split("\n"):
                w(f"+{line}")
        w("```")
    print("\n".join(out))
    return 0 if (all_ok and same_as_run and retained_same) else 1


if __name__ == "__main__":
    sys.exit(main())
