//! One-Click Deploy — packages projects and deploys to cloud platforms.

use serde::{Deserialize, Serialize};

/// Supported deployment platforms.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum DeployPlatform {
    Railway,
    Render,
    Fly,
    CustomVPS { host: String, ssh_key_path: String },
}

/// Configuration for a deployment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeployConfig {
    pub platform: DeployPlatform,
    pub project_dir: String,
    pub project_name: String,
    pub port: u16,
    pub env_vars: Vec<EnvVar>,
    pub health_check_path: String,
    pub ssl: bool,
    pub auto_restart: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnvVar {
    pub key: String,
    pub value: String,
    pub secret: bool,
}

/// Result of a deployment.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeployResult {
    pub url: String,
    pub status: DeployStatus,
    pub platform: String,
    pub ssl: bool,
    pub deploy_time_seconds: u64,
    pub container_id: Option<String>,
    pub logs: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum DeployStatus {
    Live,
    Deploying,
    Failed,
    Rollback,
}

/// A generated Dockerfile for a project.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DockerConfig {
    pub dockerfile: String,
    pub docker_compose: Option<String>,
    pub build_args: Vec<String>,
    pub exposed_ports: Vec<u16>,
    pub health_check: Option<String>,
}

/// The one-click deployment engine.
#[derive(Debug, Clone)]
pub struct LiveDeployer {
    pub default_platform: DeployPlatform,
}

impl Default for LiveDeployer {
    fn default() -> Self {
        Self {
            default_platform: DeployPlatform::Railway,
        }
    }
}

impl LiveDeployer {
    pub fn new(platform: DeployPlatform) -> Self {
        Self {
            default_platform: platform,
        }
    }

    /// Generate a Dockerfile for a project based on its tech stack.
    pub fn generate_dockerfile(&self, config: &DeployConfig) -> DockerConfig {
        let project_name = &config.project_name;
        let port = config.port;

        let dockerfile = format!(
            "# Auto-generated by Nexus OS LiveDeployer\n\
             FROM node:20-slim AS frontend\n\
             WORKDIR /app/frontend\n\
             COPY frontend/package*.json ./\n\
             RUN npm ci --production\n\
             COPY frontend/ ./\n\
             RUN npm run build\n\
             \n\
             FROM python:3.12-slim AS backend\n\
             WORKDIR /app\n\
             COPY backend/requirements.txt ./\n\
             RUN pip install --no-cache-dir -r requirements.txt\n\
             COPY backend/ ./backend/\n\
             COPY --from=frontend /app/frontend/dist ./static/\n\
             \n\
             ENV PORT={port}\n\
             ENV PROJECT_NAME={project_name}\n\
             EXPOSE {port}\n\
             \n\
             HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \\\n\
             CMD curl -f http://localhost:{port}{health} || exit 1\n\
             \n\
             CMD [\"python\", \"-m\", \"uvicorn\", \"backend.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"{port}\"]\n",
            port = port,
            project_name = project_name,
            health = config.health_check_path,
        );

        let docker_compose = Some(format!(
            "version: '3.8'\n\
             services:\n\
             {name}:\n\
                 build: .\n\
                 ports:\n\
                 - \"{port}:{port}\"\n\
                 environment:\n\
                 - PORT={port}\n\
                 restart: {restart}\n",
            name = project_name,
            port = port,
            restart = if config.auto_restart {
                "unless-stopped"
            } else {
                "no"
            },
        ));

        let health_check = Some(format!(
            "curl -f http://localhost:{port}{path} || exit 1",
            port = port,
            path = config.health_check_path,
        ));

        DockerConfig {
            dockerfile,
            docker_compose,
            build_args: vec![],
            exposed_ports: vec![port],
            health_check,
        }
    }

    /// Generate the deployment command for a given platform.
    pub fn deploy_command(&self, config: &DeployConfig) -> Result<Vec<String>, String> {
        match &config.platform {
            DeployPlatform::Railway => Ok(vec![
                "railway login".into(),
                "railway init".into(),
                format!("railway up --detach"),
            ]),
            DeployPlatform::Render => Ok(vec![
                "render login".into(),
                format!("render create --name {} --type web", config.project_name),
                "render deploy".into(),
            ]),
            DeployPlatform::Fly => Ok(vec![
                "fly auth login".into(),
                format!("fly launch --name {} --no-deploy", config.project_name),
                "fly deploy".into(),
            ]),
            DeployPlatform::CustomVPS { host, ssh_key_path } => Ok(vec![
                format!(
                    "scp -i {} -r {} {}:/app/",
                    ssh_key_path, config.project_dir, host
                ),
                format!(
                    "ssh -i {} {} 'cd /app && docker compose up -d'",
                    ssh_key_path, host
                ),
            ]),
        }
    }

    /// Get platform name string.
    pub fn platform_name(platform: &DeployPlatform) -> &str {
        match platform {
            DeployPlatform::Railway => "Railway",
            DeployPlatform::Render => "Render",
            DeployPlatform::Fly => "Fly.io",
            DeployPlatform::CustomVPS { .. } => "Custom VPS",
        }
    }

    /// Validate a deploy config before attempting deployment.
    pub fn validate_config(&self, config: &DeployConfig) -> Result<(), Vec<String>> {
        let mut errors = Vec::new();

        if config.project_name.is_empty() {
            errors.push("Project name is required".into());
        }
        if config.project_dir.is_empty() {
            errors.push("Project directory is required".into());
        }
        if config.port == 0 {
            errors.push("Port must be non-zero".into());
        }
        if config.health_check_path.is_empty() {
            errors.push("Health check path is required".into());
        }
        if !config.health_check_path.starts_with('/') {
            errors.push("Health check path must start with /".into());
        }

        if let DeployPlatform::CustomVPS {
            host, ssh_key_path, ..
        } = &config.platform
        {
            if host.is_empty() {
                errors.push("VPS host is required".into());
            }
            if ssh_key_path.is_empty() {
                errors.push("SSH key path is required for VPS deployment".into());
            }
        }

        if errors.is_empty() {
            Ok(())
        } else {
            Err(errors)
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn test_config() -> DeployConfig {
        DeployConfig {
            platform: DeployPlatform::Railway,
            project_dir: "/tmp/my-app".into(),
            project_name: "my-app".into(),
            port: 3000,
            env_vars: vec![EnvVar {
                key: "DATABASE_URL".into(),
                value: "postgres://localhost/mydb".into(),
                secret: true,
            }],
            health_check_path: "/health".into(),
            ssl: true,
            auto_restart: true,
        }
    }

    #[test]
    fn test_deployer_default() {
        let deployer = LiveDeployer::default();
        assert_eq!(deployer.default_platform, DeployPlatform::Railway);
    }

    #[test]
    fn test_generate_dockerfile() {
        let deployer = LiveDeployer::default();
        let config = test_config();
        let docker = deployer.generate_dockerfile(&config);

        assert!(docker.dockerfile.contains("FROM node:20-slim"));
        assert!(docker.dockerfile.contains("FROM python:3.12-slim"));
        assert!(docker.dockerfile.contains("EXPOSE 3000"));
        assert!(docker.dockerfile.contains("HEALTHCHECK"));
        assert!(docker.dockerfile.contains("/health"));
        assert_eq!(docker.exposed_ports, vec![3000]);
        assert!(docker.docker_compose.is_some());
        assert!(docker.health_check.is_some());
    }

    #[test]
    fn test_generate_docker_compose_auto_restart() {
        let deployer = LiveDeployer::default();
        let config = test_config();
        let docker = deployer.generate_dockerfile(&config);
        let compose = docker.docker_compose.unwrap();
        assert!(compose.contains("unless-stopped"));
    }

    #[test]
    fn test_deploy_command_railway() {
        let deployer = LiveDeployer::default();
        let config = test_config();
        let commands = deployer.deploy_command(&config).unwrap();
        assert_eq!(commands.len(), 3);
        assert!(commands[0].contains("railway login"));
    }

    #[test]
    fn test_deploy_command_fly() {
        let deployer = LiveDeployer::default();
        let mut config = test_config();
        config.platform = DeployPlatform::Fly;
        let commands = deployer.deploy_command(&config).unwrap();
        assert!(commands[0].contains("fly auth"));
        assert!(commands[1].contains("my-app"));
    }

    #[test]
    fn test_deploy_command_custom_vps() {
        let deployer = LiveDeployer::default();
        let mut config = test_config();
        config.platform = DeployPlatform::CustomVPS {
            host: "user@10.0.0.1".into(),
            ssh_key_path: "~/.ssh/id_rsa".into(),
        };
        let commands = deployer.deploy_command(&config).unwrap();
        assert!(commands[0].contains("scp"));
        assert!(commands[1].contains("docker compose"));
    }

    #[test]
    fn test_validate_config_valid() {
        let deployer = LiveDeployer::default();
        let config = test_config();
        assert!(deployer.validate_config(&config).is_ok());
    }

    #[test]
    fn test_validate_config_empty_name() {
        let deployer = LiveDeployer::default();
        let mut config = test_config();
        config.project_name = String::new();
        let errors = deployer.validate_config(&config).unwrap_err();
        assert!(errors.iter().any(|e| e.contains("Project name")));
    }

    #[test]
    fn test_validate_config_bad_health_path() {
        let deployer = LiveDeployer::default();
        let mut config = test_config();
        config.health_check_path = "health".into();
        let errors = deployer.validate_config(&config).unwrap_err();
        assert!(errors.iter().any(|e| e.contains("must start with /")));
    }

    #[test]
    fn test_validate_config_vps_missing_host() {
        let deployer = LiveDeployer::default();
        let mut config = test_config();
        config.platform = DeployPlatform::CustomVPS {
            host: String::new(),
            ssh_key_path: "~/.ssh/id_rsa".into(),
        };
        let errors = deployer.validate_config(&config).unwrap_err();
        assert!(errors.iter().any(|e| e.contains("VPS host")));
    }

    #[test]
    fn test_platform_name() {
        assert_eq!(
            LiveDeployer::platform_name(&DeployPlatform::Railway),
            "Railway"
        );
        assert_eq!(LiveDeployer::platform_name(&DeployPlatform::Fly), "Fly.io");
        assert_eq!(
            LiveDeployer::platform_name(&DeployPlatform::CustomVPS {
                host: "x".into(),
                ssh_key_path: "y".into(),
            }),
            "Custom VPS"
        );
    }
}
