//! Live App Evolution — monitors deployed applications and automatically improves them.

use serde::{Deserialize, Serialize};

/// Metrics collected from a live deployed application.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppMetrics {
    pub error_rate: f64,
    pub avg_response_ms: f64,
    pub p95_response_ms: f64,
    pub active_users: u64,
    pub requests_per_minute: f64,
    pub memory_usage_mb: f64,
    pub cpu_percent: f64,
    pub uptime_seconds: u64,
}

impl Default for AppMetrics {
    fn default() -> Self {
        Self {
            error_rate: 0.0,
            avg_response_ms: 100.0,
            p95_response_ms: 300.0,
            active_users: 0,
            requests_per_minute: 0.0,
            memory_usage_mb: 0.0,
            cpu_percent: 0.0,
            uptime_seconds: 0,
        }
    }
}

/// Monitoring configuration for a deployed app.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MonitoringConfig {
    pub check_interval_secs: u64,
    pub error_rate_threshold: f64,
    pub response_time_threshold_ms: f64,
    pub memory_threshold_mb: f64,
    pub auto_evolve: bool,
    pub require_hitl_approval: bool,
}

impl Default for MonitoringConfig {
    fn default() -> Self {
        Self {
            check_interval_secs: 300,
            error_rate_threshold: 0.05,
            response_time_threshold_ms: 2000.0,
            memory_threshold_mb: 512.0,
            auto_evolve: false,
            require_hitl_approval: true,
        }
    }
}

/// A deployed app being monitored.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DeployedApp {
    pub project_id: String,
    pub url: String,
    pub project_dir: String,
    pub monitoring: MonitoringConfig,
    pub current_metrics: Option<AppMetrics>,
    pub evolution_history: Vec<AppEvolution>,
    pub status: AppStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum AppStatus {
    Healthy,
    Degraded,
    Down,
    Evolving,
}

/// A single evolution event — an improvement applied to a deployed app.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppEvolution {
    pub timestamp_secs: u64,
    pub change_description: String,
    pub before_metrics: AppMetrics,
    pub after_metrics: Option<AppMetrics>,
    pub improvement_percent: Option<f64>,
    pub files_changed: Vec<String>,
    pub rollback_available: bool,
    pub status: EvolutionStatus,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum EvolutionStatus {
    Pending,
    Approved,
    Applied,
    Monitoring,
    Verified,
    RolledBack,
    Rejected,
}

/// An issue detected in a deployed app.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DetectedIssue {
    pub category: IssueCategory,
    pub description: String,
    pub severity: f64,
    pub metric_name: String,
    pub current_value: f64,
    pub threshold: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub enum IssueCategory {
    HighErrorRate,
    SlowResponse,
    HighMemory,
    HighCpu,
    UserDropoff,
    SecurityAnomaly,
}

/// Fix recommendation generated by analyzing an issue.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FixRecommendation {
    pub issue: DetectedIssue,
    pub description: String,
    pub estimated_improvement: f64,
    pub risk_level: f64,
    pub auto_fixable: bool,
}

/// The live app evolution engine.
#[derive(Debug, Clone)]
pub struct LiveAppEvolver {
    pub monitored_apps: Vec<DeployedApp>,
    pub monitoring_interval_secs: u64,
}

impl Default for LiveAppEvolver {
    fn default() -> Self {
        Self {
            monitored_apps: Vec::new(),
            monitoring_interval_secs: 300,
        }
    }
}

impl LiveAppEvolver {
    /// Register a deployed app for monitoring.
    pub fn register_app(&mut self, app: DeployedApp) {
        self.monitored_apps.push(app);
    }

    /// Remove an app from monitoring.
    pub fn unregister_app(&mut self, project_id: &str) -> bool {
        let before = self.monitored_apps.len();
        self.monitored_apps.retain(|a| a.project_id != project_id);
        self.monitored_apps.len() < before
    }

    /// Get a monitored app by project ID.
    pub fn get_app(&self, project_id: &str) -> Option<&DeployedApp> {
        self.monitored_apps
            .iter()
            .find(|a| a.project_id == project_id)
    }

    /// Get a mutable reference to a monitored app.
    pub fn get_app_mut(&mut self, project_id: &str) -> Option<&mut DeployedApp> {
        self.monitored_apps
            .iter_mut()
            .find(|a| a.project_id == project_id)
    }

    /// Detect issues in an app based on its current metrics.
    pub fn detect_issues(
        &self,
        metrics: &AppMetrics,
        config: &MonitoringConfig,
    ) -> Vec<DetectedIssue> {
        let mut issues = Vec::new();

        if metrics.error_rate > config.error_rate_threshold {
            issues.push(DetectedIssue {
                category: IssueCategory::HighErrorRate,
                description: format!(
                    "Error rate {:.1}% exceeds threshold {:.1}%",
                    metrics.error_rate * 100.0,
                    config.error_rate_threshold * 100.0
                ),
                severity: (metrics.error_rate / config.error_rate_threshold).min(1.0),
                metric_name: "error_rate".into(),
                current_value: metrics.error_rate,
                threshold: config.error_rate_threshold,
            });
        }

        if metrics.p95_response_ms > config.response_time_threshold_ms {
            issues.push(DetectedIssue {
                category: IssueCategory::SlowResponse,
                description: format!(
                    "P95 response time {:.0}ms exceeds {:.0}ms threshold",
                    metrics.p95_response_ms, config.response_time_threshold_ms
                ),
                severity: (metrics.p95_response_ms / config.response_time_threshold_ms).min(1.0),
                metric_name: "p95_response_ms".into(),
                current_value: metrics.p95_response_ms,
                threshold: config.response_time_threshold_ms,
            });
        }

        if metrics.memory_usage_mb > config.memory_threshold_mb {
            issues.push(DetectedIssue {
                category: IssueCategory::HighMemory,
                description: format!(
                    "Memory usage {:.0}MB exceeds {:.0}MB threshold",
                    metrics.memory_usage_mb, config.memory_threshold_mb
                ),
                severity: (metrics.memory_usage_mb / config.memory_threshold_mb).min(1.0),
                metric_name: "memory_usage_mb".into(),
                current_value: metrics.memory_usage_mb,
                threshold: config.memory_threshold_mb,
            });
        }

        if metrics.cpu_percent > 90.0 {
            issues.push(DetectedIssue {
                category: IssueCategory::HighCpu,
                description: format!("CPU usage {:.0}% is critically high", metrics.cpu_percent),
                severity: (metrics.cpu_percent / 100.0).min(1.0),
                metric_name: "cpu_percent".into(),
                current_value: metrics.cpu_percent,
                threshold: 90.0,
            });
        }

        issues
    }

    /// Build LLM prompt for generating fix recommendations.
    pub fn build_fix_prompt(&self, issues: &[DetectedIssue]) -> (String, String) {
        let system = "You are an application performance optimization engine. Given production \
                       metrics issues, recommend specific code fixes."
            .to_string();

        let issues_json = serde_json::to_string_pretty(issues).unwrap_or_else(|_| "[]".to_string());
        let user = format!(
            "The following production issues have been detected:\n{issues_json}\n\n\
             For each issue, recommend a specific code fix:\n\
             1. Description of the fix\n\
             2. Estimated improvement percentage\n\
             3. Risk level (0-1)\n\
             4. Whether it can be auto-fixed without human review\n\
             Return as JSON array matching the FixRecommendation schema."
        );
        (system, user)
    }

    /// Calculate improvement between before and after metrics.
    pub fn calculate_improvement(before: &AppMetrics, after: &AppMetrics) -> f64 {
        let mut improvements = Vec::new();

        // Lower error rate is better
        if before.error_rate > 0.0 {
            improvements.push((before.error_rate - after.error_rate) / before.error_rate);
        }

        // Lower response time is better
        if before.avg_response_ms > 0.0 {
            improvements
                .push((before.avg_response_ms - after.avg_response_ms) / before.avg_response_ms);
        }

        // Lower memory is better
        if before.memory_usage_mb > 0.0 {
            improvements
                .push((before.memory_usage_mb - after.memory_usage_mb) / before.memory_usage_mb);
        }

        if improvements.is_empty() {
            return 0.0;
        }

        let sum: f64 = improvements.iter().sum();
        (sum / improvements.len() as f64) * 100.0
    }

    /// Determine the health status of an app from metrics.
    pub fn assess_health(metrics: &AppMetrics, config: &MonitoringConfig) -> AppStatus {
        if metrics.error_rate > config.error_rate_threshold * 5.0 {
            AppStatus::Down
        } else if metrics.error_rate > config.error_rate_threshold
            || metrics.p95_response_ms > config.response_time_threshold_ms
        {
            AppStatus::Degraded
        } else {
            AppStatus::Healthy
        }
    }

    /// List all monitored apps and their status.
    pub fn list_apps(&self) -> Vec<AppStatusSummary> {
        self.monitored_apps
            .iter()
            .map(|app| AppStatusSummary {
                project_id: app.project_id.clone(),
                url: app.url.clone(),
                status: app.status.clone(),
                evolutions_count: app.evolution_history.len(),
                auto_evolve: app.monitoring.auto_evolve,
            })
            .collect()
    }
}

/// Summary of monitored app status for UI display.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppStatusSummary {
    pub project_id: String,
    pub url: String,
    pub status: AppStatus,
    pub evolutions_count: usize,
    pub auto_evolve: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    fn healthy_metrics() -> AppMetrics {
        AppMetrics {
            error_rate: 0.01,
            avg_response_ms: 150.0,
            p95_response_ms: 400.0,
            active_users: 50,
            requests_per_minute: 200.0,
            memory_usage_mb: 256.0,
            cpu_percent: 45.0,
            uptime_seconds: 86400,
        }
    }

    fn degraded_metrics() -> AppMetrics {
        AppMetrics {
            error_rate: 0.15,
            avg_response_ms: 3000.0,
            p95_response_ms: 5000.0,
            active_users: 30,
            requests_per_minute: 100.0,
            memory_usage_mb: 700.0,
            cpu_percent: 95.0,
            uptime_seconds: 86400,
        }
    }

    fn test_app() -> DeployedApp {
        DeployedApp {
            project_id: "proj-1".into(),
            url: "https://my-app.railway.app".into(),
            project_dir: "/tmp/my-app".into(),
            monitoring: MonitoringConfig::default(),
            current_metrics: Some(healthy_metrics()),
            evolution_history: vec![],
            status: AppStatus::Healthy,
        }
    }

    #[test]
    fn test_register_and_get_app() {
        let mut evolver = LiveAppEvolver::default();
        evolver.register_app(test_app());
        assert_eq!(evolver.monitored_apps.len(), 1);
        assert!(evolver.get_app("proj-1").is_some());
        assert!(evolver.get_app("nonexistent").is_none());
    }

    #[test]
    fn test_unregister_app() {
        let mut evolver = LiveAppEvolver::default();
        evolver.register_app(test_app());
        assert!(evolver.unregister_app("proj-1"));
        assert!(!evolver.unregister_app("proj-1"));
        assert_eq!(evolver.monitored_apps.len(), 0);
    }

    #[test]
    fn test_detect_issues_healthy() {
        let evolver = LiveAppEvolver::default();
        let config = MonitoringConfig::default();
        let issues = evolver.detect_issues(&healthy_metrics(), &config);
        assert!(issues.is_empty());
    }

    #[test]
    fn test_detect_issues_degraded() {
        let evolver = LiveAppEvolver::default();
        let config = MonitoringConfig::default();
        let issues = evolver.detect_issues(&degraded_metrics(), &config);
        assert!(!issues.is_empty());

        let categories: Vec<&IssueCategory> = issues.iter().map(|i| &i.category).collect();
        assert!(categories.contains(&&IssueCategory::HighErrorRate));
        assert!(categories.contains(&&IssueCategory::SlowResponse));
        assert!(categories.contains(&&IssueCategory::HighMemory));
        assert!(categories.contains(&&IssueCategory::HighCpu));
    }

    #[test]
    fn test_calculate_improvement_positive() {
        let before = degraded_metrics();
        let after = healthy_metrics();
        let improvement = LiveAppEvolver::calculate_improvement(&before, &after);
        assert!(improvement > 0.0, "Expected positive improvement");
    }

    #[test]
    fn test_calculate_improvement_negative() {
        let before = healthy_metrics();
        let after = degraded_metrics();
        let improvement = LiveAppEvolver::calculate_improvement(&before, &after);
        assert!(improvement < 0.0, "Expected negative improvement");
    }

    #[test]
    fn test_assess_health() {
        let config = MonitoringConfig::default();
        assert_eq!(
            LiveAppEvolver::assess_health(&healthy_metrics(), &config),
            AppStatus::Healthy
        );
        assert_eq!(
            LiveAppEvolver::assess_health(&degraded_metrics(), &config),
            AppStatus::Degraded
        );

        let down_metrics = AppMetrics {
            error_rate: 0.5,
            ..Default::default()
        };
        assert_eq!(
            LiveAppEvolver::assess_health(&down_metrics, &config),
            AppStatus::Down
        );
    }

    #[test]
    fn test_list_apps() {
        let mut evolver = LiveAppEvolver::default();
        evolver.register_app(test_app());
        let list = evolver.list_apps();
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].project_id, "proj-1");
        assert_eq!(list[0].status, AppStatus::Healthy);
    }

    #[test]
    fn test_build_fix_prompt() {
        let evolver = LiveAppEvolver::default();
        let issues = vec![DetectedIssue {
            category: IssueCategory::HighErrorRate,
            description: "High error rate".into(),
            severity: 0.8,
            metric_name: "error_rate".into(),
            current_value: 0.15,
            threshold: 0.05,
        }];
        let (system, user) = evolver.build_fix_prompt(&issues);
        assert!(system.contains("optimization"));
        assert!(user.contains("error_rate"));
    }
}
