import { useState, useEffect, useCallback, useMemo } from "react";
import { hasDesktopRuntime, emailList, emailSave, emailDelete } from "../api/backend";
import {
  Inbox, Star, Send, FileEdit, Mail, Archive, Trash2,
  Pen, FileText, CornerDownLeft, Loader, MailOpen, StarOff,
  AlertCircle, SendHorizonal,
} from "lucide-react";
import "./email-client.css";

/* ─── types ─── */
type FolderId = "inbox" | "sent" | "drafts" | "starred" | "outbox" | "archive" | "trash";
type Priority = "high" | "normal" | "low";
type Category = "primary" | "updates" | "social" | "promotions" | "agent";

interface Email {
  id: string;
  threadId: string;
  from: { name: string; email: string };
  to: { name: string; email: string }[];
  cc?: { name: string; email: string }[];
  subject: string;
  body: string;
  timestamp: number;
  read: boolean;
  starred: boolean;
  folder: FolderId;
  priority: Priority;
  category: Category;
  labels: string[];
}

interface EmailTemplate {
  id: string;
  name: string;
  subject: string;
  body: string;
  category: string;
}

/* ─── constants ─── */
const FOLDERS: { id: FolderId; label: string; icon: React.ReactNode }[] = [
  { id: "inbox", label: "Inbox", icon: <Inbox size={14} /> },
  { id: "starred", label: "Starred", icon: <Star size={14} /> },
  { id: "sent", label: "Sent", icon: <Send size={14} /> },
  { id: "drafts", label: "Drafts", icon: <FileEdit size={14} /> },
  { id: "outbox", label: "Outbox", icon: <SendHorizonal size={14} /> },
  { id: "archive", label: "Archive", icon: <Archive size={14} /> },
  { id: "trash", label: "Trash", icon: <Trash2 size={14} /> },
];

const CATEGORY_COLORS: Record<Category, string> = {
  primary: "var(--nexus-accent)",
  updates: "#38bdf8",
  social: "#a78bfa",
  promotions: "#fbbf24",
  agent: "#818cf8",
};

const TEMPLATES: EmailTemplate[] = [
  { id: "tmpl-1", name: "Bug Report Response", subject: "Re: Bug Report — {{issue}}", body: "Hi {{name}},\n\nThank you for reporting this issue. Our team has investigated and here's what we found:\n\n**Issue:** {{issue}}\n**Status:** Under review\n**Priority:** {{priority}}\n\nWe'll keep you updated on the fix.\n\nBest,\nNexus OS Team", category: "support" },
  { id: "tmpl-2", name: "Feature Announcement", subject: "New in Nexus OS: {{feature}}", body: "Hello {{name}},\n\nWe're excited to announce a new feature in Nexus OS:\n\n## {{feature}}\n\n{{description}}\n\nThis feature is available in the latest release. Update now to try it out.\n\nBest,\nNexus OS Team", category: "announcement" },
  { id: "tmpl-3", name: "Agent Status Report", subject: "Weekly Agent Performance Report", body: "Hi Team,\n\n## Agent Performance Summary\n\n- **Tasks Completed:** {{tasks}}\n- **Fuel Used:** {{fuel}}\n- **Success Rate:** {{rate}}\n\nTop performing agent: {{topAgent}}\n\nDetailed metrics attached.\n\nGenerated by Planner Agent", category: "report" },
  { id: "tmpl-4", name: "Onboarding Welcome", subject: "Welcome to Nexus OS!", body: "Hello {{name}},\n\nWelcome to Nexus OS — the governed AI operating system.\n\nHere's how to get started:\n1. Set up your agents in the Agents panel\n2. Configure governance rules\n3. Start your first workflow\n\nIf you need help, visit the Learning Center.\n\nBest,\nNexus OS Team", category: "onboarding" },
];

/* ─── persistence helpers ─── */
async function loadEmails(): Promise<Email[]> {
  if (!hasDesktopRuntime()) return [];
  try {
    const raw = await emailList();
    return JSON.parse(raw) as Email[];
  } catch {
    return [];
  }
}

async function persistEmail(email: Email): Promise<void> {
  if (!hasDesktopRuntime()) return;
  try {
    await emailSave(email.id, JSON.stringify(email));
  } catch (e) {
    if (import.meta.env.DEV) console.error("Failed to save email:", e);
  }
}

async function removeEmail(id: string): Promise<void> {
  if (!hasDesktopRuntime()) return;
  try {
    await emailDelete(id);
  } catch (e) {
    if (import.meta.env.DEV) console.error("Failed to delete email:", e);
  }
}

/* ─── component ─── */
export default function EmailClient() {
  const [emails, setEmails] = useState<Email[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [selectedFolder, setSelectedFolder] = useState<FolderId>("inbox");
  const [selectedEmailId, setSelectedEmailId] = useState<string | null>(null);
  const [showCompose, setShowCompose] = useState(false);
  const [showTemplates, setShowTemplates] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [filterCategory, setFilterCategory] = useState<Category | "all">("all");
  const [sortBy, setSortBy] = useState<"date" | "priority" | "unread">("date");
  const [auditLog, setAuditLog] = useState<string[]>([]);

  // compose state
  const [composeTo, setComposeTo] = useState("");
  const [composeSubject, setComposeSubject] = useState("");
  const [composeBody, setComposeBody] = useState("");

  const selectedEmail = useMemo(() => emails.find(e => e.id === selectedEmailId), [emails, selectedEmailId]);

  /* ─── load on mount ─── */
  useEffect(() => {
    loadEmails().then(loaded => {
      setEmails(loaded);
      setLoaded(true);
      if (loaded.length > 0) logAudit(`Loaded ${loaded.length} emails from disk`);
    });
  }, []);

  /* ─── filtered emails ─── */
  const filteredEmails = useMemo(() => {
    let list = selectedFolder === "starred"
      ? emails.filter(e => e.starred)
      : emails.filter(e => e.folder === selectedFolder);
    if (filterCategory !== "all") list = list.filter(e => e.category === filterCategory);
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      list = list.filter(e => e.subject.toLowerCase().includes(q) || e.from.name.toLowerCase().includes(q) || e.body.toLowerCase().includes(q));
    }
    list = [...list].sort((a, b) => {
      if (sortBy === "priority") {
        const p: Record<Priority, number> = { high: 0, normal: 1, low: 2 };
        return p[a.priority] - p[b.priority] || b.timestamp - a.timestamp;
      }
      if (sortBy === "unread") return (a.read ? 1 : 0) - (b.read ? 1 : 0) || b.timestamp - a.timestamp;
      return b.timestamp - a.timestamp;
    });
    return list;
  }, [emails, selectedFolder, filterCategory, searchQuery, sortBy]);

  /* ─── thread ─── */
  const thread = useMemo(() => {
    if (!selectedEmail) return [];
    return emails.filter(e => e.threadId === selectedEmail.threadId).sort((a, b) => a.timestamp - b.timestamp);
  }, [emails, selectedEmail]);

  /* ─── counts ─── */
  const folderCounts = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const f of FOLDERS) {
      if (f.id === "starred") {
        counts[f.id] = emails.filter(e => e.starred && !e.read).length;
      } else {
        counts[f.id] = emails.filter(e => e.folder === f.id && !e.read).length;
      }
    }
    return counts;
  }, [emails]);

  /* ─── handlers ─── */
  const updateAndPersist = useCallback((id: string, updater: (e: Email) => Email) => {
    setEmails(prev => prev.map(e => {
      if (e.id !== id) return e;
      const updated = updater(e);
      persistEmail(updated);
      return updated;
    }));
  }, []);

  const markRead = useCallback((id: string) => {
    updateAndPersist(id, e => ({ ...e, read: true }));
  }, [updateAndPersist]);

  const toggleStar = useCallback((id: string) => {
    updateAndPersist(id, e => ({ ...e, starred: !e.starred }));
  }, [updateAndPersist]);

  const moveToFolder = useCallback((id: string, folder: FolderId) => {
    updateAndPersist(id, e => ({ ...e, folder }));
    if (selectedEmailId === id) setSelectedEmailId(null);
    logAudit(`Moved email to ${folder}`);
  }, [selectedEmailId, updateAndPersist]);

  const deleteEmailHandler = useCallback((id: string) => {
    const email = emails.find(e => e.id === id);
    if (email?.folder === "trash") {
      setEmails(prev => prev.filter(e => e.id !== id));
      removeEmail(id);
    } else {
      moveToFolder(id, "trash");
    }
    if (selectedEmailId === id) setSelectedEmailId(null);
  }, [emails, selectedEmailId, moveToFolder]);

  const saveDraft = useCallback(() => {
    if (!composeTo.trim() && !composeSubject.trim() && !composeBody.trim()) return;
    const email: Email = {
      id: `em-${Date.now()}`, threadId: `t-${Date.now()}`,
      from: { name: "You", email: "you@nexus-os.local" },
      to: composeTo.trim() ? [{ name: composeTo.split("@")[0], email: composeTo }] : [],
      subject: composeSubject, body: composeBody,
      timestamp: Date.now(), read: true, starred: false, folder: "drafts",
      priority: "normal", category: "primary", labels: [],
    };
    setEmails(prev => [email, ...prev]);
    persistEmail(email);
    setComposeTo(""); setComposeSubject(""); setComposeBody("");
    setShowCompose(false);
    logAudit("Draft saved to disk");
  }, [composeTo, composeSubject, composeBody]);

  const sendEmail = useCallback(() => {
    if (!composeTo.trim() || !composeSubject.trim()) return;
    const email: Email = {
      id: `em-${Date.now()}`, threadId: `t-${Date.now()}`,
      from: { name: "You", email: "you@nexus-os.local" },
      to: [{ name: composeTo.split("@")[0], email: composeTo }],
      subject: composeSubject, body: composeBody,
      timestamp: Date.now(), read: true, starred: false, folder: "outbox",
      priority: "normal", category: "primary", labels: [],
    };
    setEmails(prev => [email, ...prev]);
    persistEmail(email);
    setComposeTo(""); setComposeSubject(""); setComposeBody("");
    setShowCompose(false);
    logAudit(`Email queued in Outbox to ${composeTo}`);
  }, [composeTo, composeSubject, composeBody]);

  const applyTemplate = useCallback((tmpl: EmailTemplate) => {
    setComposeSubject(tmpl.subject);
    setComposeBody(tmpl.body);
    setShowTemplates(false);
    logAudit(`Template applied: ${tmpl.name}`);
  }, []);

  const logAudit = (msg: string) => setAuditLog(prev => [msg, ...prev].slice(0, 20));

  const formatTime = (ts: number) => {
    const diff = Date.now() - ts;
    if (diff < 60000) return "now";
    if (diff < 3600000) return `${Math.floor(diff / 60000)}m`;
    if (diff < 86400000) return `${Math.floor(diff / 3600000)}h`;
    return `${Math.floor(diff / 86400000)}d`;
  };

  const formatDate = (ts: number) => new Date(ts).toLocaleString();

  /* ─── render ─── */
  return (
    <div className="ec-container">
      {/* ─── Sidebar ─── */}
      <aside className="ec-sidebar">
        <div className="ec-sidebar-header">
          <h2 className="ec-sidebar-title">Mail</h2>
          <button className="ec-btn-compose cursor-pointer" onClick={() => { setShowCompose(true); setShowTemplates(false); }}><Pen size={12} style={{ display: "inline", verticalAlign: "middle", marginRight: 4 }} />Compose</button>
        </div>

        {/* SMTP notice */}
        <div className="ec-pii-notice" style={{ margin: "0 8px 8px", fontSize: 11 }}>
          <span className="ec-pii-icon"><SendHorizonal size={12} /></span>
          Local drafts mode. Connect SMTP in Settings to send externally.
        </div>

        {/* folders */}
        <div className="ec-folders">
          {FOLDERS.map(folder => (
            <button key={folder.id} className={`ec-folder ${selectedFolder === folder.id ? "active" : ""}`} onClick={() => { setSelectedFolder(folder.id); setSelectedEmailId(null); setFilterCategory("all"); }}>
              <span className="ec-folder-icon">{folder.icon}</span>
              <span className="ec-folder-label">{folder.label}</span>
              {folderCounts[folder.id] > 0 && <span className="ec-folder-badge">{folderCounts[folder.id]}</span>}
            </button>
          ))}
        </div>

        {/* categories */}
        <div className="ec-categories">
          <div className="ec-cat-header">Categories</div>
          {(["all", "primary", "updates", "social", "promotions", "agent"] as const).map(cat => (
            <button key={cat} className={`ec-cat-btn ${filterCategory === cat ? "active" : ""}`} onClick={() => setFilterCategory(cat)}>
              {cat !== "all" && <span className="ec-cat-dot" style={{ background: CATEGORY_COLORS[cat as Category] }} />}
              {cat === "all" ? "All" : cat.charAt(0).toUpperCase() + cat.slice(1)}
            </button>
          ))}
        </div>

        {/* audit */}
        <div className="ec-audit-section">
          <div className="ec-audit-header">Activity</div>
          {auditLog.slice(0, 4).map((msg, i) => (
            <div key={i} className="ec-audit-entry">{msg}</div>
          ))}
        </div>
      </aside>

      {/* ─── Email List ─── */}
      <div className="ec-email-list">
        <div className="ec-list-header">
          <input className="ec-search" placeholder="Search emails..." value={searchQuery} onChange={e => setSearchQuery(e.target.value)} />
          <select className="ec-sort-select" value={sortBy} onChange={e => setSortBy(e.target.value as typeof sortBy)}>
            <option value="date">Date</option>
            <option value="priority">Priority</option>
            <option value="unread">Unread First</option>
          </select>
        </div>
        <div className="ec-list-items">
          {!loaded && (
            <div className="ec-empty">
              <div className="ec-empty-icon"><Loader size={24} /></div>
              <div>Loading emails...</div>
            </div>
          )}
          {loaded && filteredEmails.length === 0 && (
            <div className="ec-empty">
              <div className="ec-empty-icon"><MailOpen size={24} /></div>
              <div>{emails.length === 0 ? "No emails yet — compose your first draft" : "No emails in this folder"}</div>
            </div>
          )}
          {filteredEmails.map(email => (
            <div key={email.id} className={`ec-email-item ${!email.read ? "unread" : ""} ${selectedEmailId === email.id ? "active" : ""}`} onClick={() => { setSelectedEmailId(email.id); markRead(email.id); }}>
              <div className="ec-email-item-left">
                <button className="ec-star-btn cursor-pointer" onClick={e => { e.stopPropagation(); toggleStar(email.id); }}>{email.starred ? <Star size={14} fill="currentColor" /> : <StarOff size={14} />}</button>
              </div>
              <div className="ec-email-item-main">
                <div className="ec-email-from">{email.from.name}</div>
                <div className="ec-email-subject">
                  {email.priority === "high" && <span className="ec-priority-mark"><AlertCircle size={12} /></span>}
                  {email.subject || "(no subject)"}
                </div>
                <div className="ec-email-snippet">{email.body.slice(0, 80).replace(/\n/g, " ")}...</div>
              </div>
              <div className="ec-email-item-right">
                <span className="ec-email-time">{formatTime(email.timestamp)}</span>
                <span className="ec-email-cat" style={{ background: CATEGORY_COLORS[email.category] + "22", color: CATEGORY_COLORS[email.category] }}>{email.category}</span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ─── Email Detail / Compose ─── */}
      <div className="ec-detail">
        {/* compose */}
        {showCompose && (
          <div className="ec-compose">
            <div className="ec-compose-header">
              <span>New Email</span>
              <div className="ec-compose-actions">
                <button className="ec-btn-template cursor-pointer" onClick={() => setShowTemplates(!showTemplates)}><FileText size={12} style={{ display: "inline", verticalAlign: "middle", marginRight: 4 }} />Templates</button>
                <button className="ec-compose-close" onClick={() => setShowCompose(false)}>×</button>
              </div>
            </div>

            {showTemplates && (
              <div className="ec-templates-panel">
                <div className="ec-templates-header">Templates</div>
                {TEMPLATES.map(tmpl => (
                  <div key={tmpl.id} className="ec-template-item" onClick={() => applyTemplate(tmpl)}>
                    <div className="ec-template-name">{tmpl.name}</div>
                    <div className="ec-template-meta">{tmpl.category}</div>
                  </div>
                ))}
              </div>
            )}

            <div className="ec-compose-fields">
              <div className="ec-compose-field">
                <label>To</label>
                <input value={composeTo} onChange={e => setComposeTo(e.target.value)} placeholder="recipient@example.com" />
              </div>
              <div className="ec-compose-field">
                <label>Subject</label>
                <input value={composeSubject} onChange={e => setComposeSubject(e.target.value)} placeholder="Subject" />
              </div>
            </div>
            <textarea className="ec-compose-body" value={composeBody} onChange={e => setComposeBody(e.target.value)} placeholder="Write your email..." />
            <div className="ec-compose-footer">
              <button className="ec-btn-send" onClick={sendEmail} disabled={!composeTo.trim() || !composeSubject.trim()} title="Moves to Outbox — connect SMTP in Settings to send externally">Send to Outbox</button>
              <button className="ec-btn-draft" onClick={saveDraft}>Save Draft</button>
              <span className="ec-compose-fuel" style={{ opacity: 0.7 }}><SendHorizonal size={12} style={{ display: "inline", verticalAlign: "middle", marginRight: 4 }} />Outbox — connect SMTP in Settings to send</span>
            </div>
          </div>
        )}

        {/* email detail */}
        {!showCompose && selectedEmail && (
          <div className="ec-email-detail">
            <div className="ec-detail-header">
              <div className="ec-detail-subject-row">
                <h2 className="ec-detail-subject">{selectedEmail.subject || "(no subject)"}</h2>
                {selectedEmail.priority === "high" && <span className="ec-detail-priority">High Priority</span>}
              </div>
              <div className="ec-detail-actions">
                <button className="ec-action-btn cursor-pointer" onClick={() => moveToFolder(selectedEmail.id, "archive")} title="Archive"><Archive size={14} /></button>
                <button className="ec-action-btn cursor-pointer" onClick={() => deleteEmailHandler(selectedEmail.id)} title="Delete"><Trash2 size={14} /></button>
                <button className="ec-action-btn cursor-pointer" onClick={() => toggleStar(selectedEmail.id)} title="Star">{selectedEmail.starred ? <Star size={14} fill="currentColor" /> : <StarOff size={14} />}</button>
                <button className="ec-action-btn cursor-pointer" onClick={() => { setShowCompose(true); setComposeTo(selectedEmail.from.email); setComposeSubject(`Re: ${selectedEmail.subject}`); }} title="Reply"><CornerDownLeft size={14} /></button>
              </div>
            </div>

            {/* labels */}
            {selectedEmail.labels.length > 0 && (
              <div className="ec-detail-labels">
                {selectedEmail.labels.map(label => (
                  <span key={label} className="ec-label">{label}</span>
                ))}
                <span className="ec-label ec-label-cat" style={{ background: CATEGORY_COLORS[selectedEmail.category] + "22", color: CATEGORY_COLORS[selectedEmail.category] }}>{selectedEmail.category}</span>
              </div>
            )}

            {/* outbox notice */}
            {selectedEmail.folder === "outbox" && (
              <div className="ec-pii-notice">
                <span className="ec-pii-icon"><SendHorizonal size={12} /></span>
                Outbox — connect SMTP in Settings to send this email externally.
              </div>
            )}

            {/* thread */}
            <div className="ec-thread">
              {thread.map(email => (
                <div key={email.id} className={`ec-thread-msg ${email.id === selectedEmail.id ? "current" : ""}`}>
                  <div className="ec-thread-header">
                    <div className="ec-thread-from">
                      <span className="ec-thread-avatar">{email.from.name.charAt(0)}</span>
                      <div className="ec-thread-from-info">
                        <span className="ec-thread-name">{email.from.name}</span>
                        <span className="ec-thread-email">&lt;{email.from.email}&gt;</span>
                      </div>
                    </div>
                    <div className="ec-thread-meta">
                      <span className="ec-thread-date">{formatDate(email.timestamp)}</span>
                    </div>
                  </div>
                  <div className="ec-thread-to">
                    To: {email.to.map(t => t.email).join(", ")}
                    {email.cc && email.cc.length > 0 && ` · CC: ${email.cc.map(c => c.email).join(", ")}`}
                  </div>
                  <div className="ec-thread-body">{email.body}</div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* no email selected */}
        {!showCompose && !selectedEmail && (
          <div className="ec-no-email">
            <div className="ec-no-email-icon"><Mail size={32} /></div>
            <div>Select an email to read, or compose a new draft</div>
          </div>
        )}
      </div>

      {/* ─── Status Bar ─── */}
      <div className="ec-status-bar">
        <span className="ec-status-item">{FOLDERS.find(f => f.id === selectedFolder)?.label}</span>
        <span className="ec-status-item">{filteredEmails.length} emails</span>
        <span className="ec-status-item">{emails.filter(e => !e.read).length} unread</span>
        <span className="ec-status-item">{emails.filter(e => e.folder === "outbox").length} in outbox</span>
        <span className="ec-status-item ec-status-right">Local drafts mode</span>
      </div>
    </div>
  );
}
