import { useState, useCallback, useMemo } from "react";
import "./email-client.css";

/* ─── types ─── */
type FolderId = "inbox" | "sent" | "drafts" | "starred" | "archive" | "trash" | "agent-drafts";
type Priority = "high" | "normal" | "low";
type Category = "primary" | "updates" | "social" | "promotions" | "agent";

interface EmailAccount {
  id: string;
  name: string;
  email: string;
  provider: "gmail" | "outlook" | "custom";
  status: "connected" | "disconnected";
  icon: string;
}

interface EmailAttachment {
  name: string;
  size: number;
  type: string;
}

interface Email {
  id: string;
  threadId: string;
  from: { name: string; email: string };
  to: { name: string; email: string }[];
  cc?: { name: string; email: string }[];
  subject: string;
  body: string;
  bodyHtml: string;
  timestamp: number;
  read: boolean;
  starred: boolean;
  folder: FolderId;
  priority: Priority;
  category: Category;
  labels: string[];
  attachments: EmailAttachment[];
  agentDrafted?: string;
  piiRedacted?: boolean;
  hitlApproval?: "pending" | "approved" | "denied";
}

interface EmailTemplate {
  id: string;
  name: string;
  subject: string;
  body: string;
  agent: string;
  category: string;
}

/* ─── constants ─── */
const FOLDERS: { id: FolderId; label: string; icon: string }[] = [
  { id: "inbox", label: "Inbox", icon: "📥" },
  { id: "starred", label: "Starred", icon: "⭐" },
  { id: "sent", label: "Sent", icon: "📤" },
  { id: "drafts", label: "Drafts", icon: "📝" },
  { id: "agent-drafts", label: "Agent Drafts", icon: "⬢" },
  { id: "archive", label: "Archive", icon: "📦" },
  { id: "trash", label: "Trash", icon: "🗑" },
];

const CATEGORY_COLORS: Record<Category, string> = {
  primary: "#22d3ee",
  updates: "#38bdf8",
  social: "#a78bfa",
  promotions: "#fbbf24",
  agent: "#818cf8",
};

const ACCOUNTS: EmailAccount[] = [
  { id: "acc-1", name: "Suresh Karicheti", email: "suresh@nexus-os.dev", provider: "gmail", status: "connected", icon: "G" },
  { id: "acc-2", name: "Nexus Team", email: "team@nexus-os.dev", provider: "outlook", status: "connected", icon: "O" },
  { id: "acc-3", name: "Personal", email: "suresh.dev@proton.me", provider: "custom", status: "disconnected", icon: "P" },
];

const TEMPLATES: EmailTemplate[] = [
  { id: "tmpl-1", name: "Bug Report Response", subject: "Re: Bug Report — {{issue}}", body: "Hi {{name}},\n\nThank you for reporting this issue. Our team has investigated and here's what we found:\n\n**Issue:** {{issue}}\n**Status:** Under review\n**Priority:** {{priority}}\n\nWe'll keep you updated on the fix.\n\nBest,\nNexus OS Team", agent: "Content Agent", category: "support" },
  { id: "tmpl-2", name: "Feature Announcement", subject: "New in Nexus OS: {{feature}}", body: "Hello {{name}},\n\nWe're excited to announce a new feature in Nexus OS:\n\n## {{feature}}\n\n{{description}}\n\nThis feature is available in the latest release. Update now to try it out.\n\nBest,\nNexus OS Team", agent: "Content Agent", category: "announcement" },
  { id: "tmpl-3", name: "Agent Status Report", subject: "Weekly Agent Performance Report", body: "Hi Team,\n\n## Agent Performance Summary\n\n- **Tasks Completed:** {{tasks}}\n- **Fuel Used:** {{fuel}}\n- **Success Rate:** {{rate}}\n\nTop performing agent: {{topAgent}}\n\nDetailed metrics attached.\n\nGenerated by Planner Agent", agent: "Planner Agent", category: "report" },
  { id: "tmpl-4", name: "Onboarding Welcome", subject: "Welcome to Nexus OS!", body: "Hello {{name}},\n\nWelcome to Nexus OS — the governed AI operating system.\n\nHere's how to get started:\n1. Set up your agents in the Agents panel\n2. Configure governance rules\n3. Start your first workflow\n\nIf you need help, visit the Learning Center.\n\nBest,\nNexus OS Team", agent: "Content Agent", category: "onboarding" },
];

const INITIAL_EMAILS: Email[] = [
  {
    id: "em-1", threadId: "t-1", from: { name: "GitHub", email: "noreply@github.com" },
    to: [{ name: "Suresh", email: "suresh@nexus-os.dev" }], subject: "PR #47 merged: fix fuel accounting race condition",
    body: "Pull request #47 has been merged into main.\n\nChanges:\n- Added atomic compare-and-swap for FuelLedger\n- Regression test for concurrent fuel deduction\n- 3 files changed, +47 -12\n\nMerged by: Self-Improve Agent",
    bodyHtml: "", timestamp: Date.now() - 1800000, read: false, starred: true, folder: "inbox",
    priority: "high", category: "updates", labels: ["github", "engineering"],
    attachments: [], piiRedacted: false,
  },
  {
    id: "em-2", threadId: "t-2", from: { name: "Coder Agent", email: "coder@nexus-os.local" },
    to: [{ name: "Suresh", email: "suresh@nexus-os.dev" }], subject: "[HITL] Agent requests approval to send deployment notification",
    body: "Coder Agent has drafted an email to notify the team about the Phase 7 deployment.\n\n--- DRAFT ---\nTo: team@nexus-os.dev\nSubject: Phase 7 Apps Deployed\n\nHi Team,\n\nPhase 7 apps are now live:\n- Code Editor, Terminal, File Manager\n- System Monitor, Notes App, Project Manager\n- Database Manager, API Client, Design Studio\n\nPlease test and report any issues.\n--- END DRAFT ---\n\nThis email requires your approval before sending.",
    bodyHtml: "", timestamp: Date.now() - 3600000, read: false, starred: false, folder: "agent-drafts",
    priority: "high", category: "agent", labels: ["hitl", "deployment"],
    attachments: [], agentDrafted: "Coder Agent", hitlApproval: "pending", piiRedacted: true,
  },
  {
    id: "em-3", threadId: "t-3", from: { name: "Research Agent", email: "research@nexus-os.local" },
    to: [{ name: "Suresh", email: "suresh@nexus-os.dev" }], subject: "[HITL] Research summary ready — WASM runtime comparison",
    body: "Research Agent has completed the WASM runtime comparison and wants to email the findings to the engineering channel.\n\n--- DRAFT ---\nTo: engineering@nexus-os.dev\nSubject: WASM Runtime Comparison Results\n\nKey findings:\n- Wasmtime: Best security model, capability-based\n- Wasmer: Best performance, broader language support\n- Recommendation: Wasmtime for production\n\nFull report attached.\n--- END DRAFT ---\n\nPII check: [REDACTED_EMAIL] found and masked in source data.\nThis email requires your approval.",
    bodyHtml: "", timestamp: Date.now() - 7200000, read: true, starred: false, folder: "agent-drafts",
    priority: "normal", category: "agent", labels: ["hitl", "research"],
    attachments: [{ name: "wasm-comparison.pdf", size: 245000, type: "application/pdf" }],
    agentDrafted: "Research Agent", hitlApproval: "pending", piiRedacted: true,
  },
  {
    id: "em-4", threadId: "t-4", from: { name: "Vercel", email: "notifications@vercel.com" },
    to: [{ name: "Suresh", email: "suresh@nexus-os.dev" }], subject: "Deployment successful — nexus-os.vercel.app",
    body: "Your deployment was successful.\n\nProject: nexus-os\nDomain: nexus-os.vercel.app\nBranch: main\nCommit: 92eea41\nDuration: 45s\n\nAll checks passed.",
    bodyHtml: "", timestamp: Date.now() - 14400000, read: true, starred: false, folder: "inbox",
    priority: "normal", category: "updates", labels: ["deployment"],
    attachments: [],
  },
  {
    id: "em-5", threadId: "t-5", from: { name: "Anthropic", email: "api-updates@anthropic.com" },
    to: [{ name: "Suresh", email: "suresh@nexus-os.dev" }], subject: "Claude 4.5 model family now available",
    body: "Hi Suresh,\n\nWe're excited to announce the Claude 4.5 model family is now available:\n\n- Claude Opus 4.5: Most capable model\n- Claude Sonnet 4.5: Best balance of speed and capability\n- Claude Haiku 4.5: Fastest model\n\nUpdate your API integration to use the latest models.\n\nBest,\nThe Anthropic Team",
    bodyHtml: "", timestamp: Date.now() - 86400000, read: true, starred: true, folder: "inbox",
    priority: "normal", category: "primary", labels: ["ai", "api"],
    attachments: [],
  },
  {
    id: "em-6", threadId: "t-6", from: { name: "Slack", email: "feedback@slack.com" },
    to: [{ name: "Suresh", email: "suresh@nexus-os.dev" }], subject: "Your weekly Slack digest",
    body: "Here's what you missed this week in your Slack workspaces:\n\n#general: 42 messages\n#engineering: 128 messages\n#nexus-dev: 87 messages\n\nTop conversations:\n- WASM sandbox performance discussion\n- Phase 7 app reviews\n- Fuel optimization proposals",
    bodyHtml: "", timestamp: Date.now() - 86400000 * 2, read: true, starred: false, folder: "inbox",
    priority: "low", category: "social", labels: ["slack"],
    attachments: [],
  },
  {
    id: "em-7", threadId: "t-7", from: { name: "Product Hunt", email: "digest@producthunt.com" },
    to: [{ name: "Suresh", email: "suresh@nexus-os.dev" }], subject: "Top products this week — AI dev tools",
    body: "This week's top AI developer tools:\n\n1. CodeAssist Pro — AI pair programmer\n2. DevGov — Governance for AI agents\n3. AutoDeploy — One-click deployments\n\nNexus OS was mentioned in 3 discussions!",
    bodyHtml: "", timestamp: Date.now() - 86400000 * 3, read: true, starred: false, folder: "inbox",
    priority: "low", category: "promotions", labels: [],
    attachments: [],
  },
  {
    id: "em-8", threadId: "t-1", from: { name: "Suresh", email: "suresh@nexus-os.dev" },
    to: [{ name: "Self-Improve Agent", email: "self-improve@nexus-os.local" }], subject: "Re: PR #47 merged: fix fuel accounting race condition",
    body: "Great work on this fix. The atomic CAS approach is clean.\n\nCan you also add a benchmark test to ensure there's no performance regression under high contention?",
    bodyHtml: "", timestamp: Date.now() - 1200000, read: true, starred: false, folder: "sent",
    priority: "normal", category: "primary", labels: ["github", "engineering"],
    attachments: [],
  },
  {
    id: "em-9", threadId: "t-8", from: { name: "Suresh", email: "suresh@nexus-os.dev" },
    to: [{ name: "Team", email: "team@nexus-os.dev" }], subject: "Phase 7 progress update",
    body: "Hi team,\n\nPhase 7 update:\n\nDone:\n- Code Editor (7.1)\n- Design Studio (7.2)\n- Terminal (7.3)\n- File Manager (7.4)\n- Database Manager (7.5)\n- API Client (7.6)\n- Notes App (7.7)\n- Project Manager (7.9)\n- System Monitor (7.11)\n\nIn progress:\n- Email Client (7.8)\n\nRemaining:\n- Media Studio (7.10)\n- App Store (7.12)\n- AI Chat Hub (7.13)\n- Deploy Pipeline (7.14)\n- Learning Center (7.15)\n\nWe're making great progress. Keep it up!",
    bodyHtml: "", timestamp: Date.now() - 43200000, read: true, starred: false, folder: "sent",
    priority: "normal", category: "primary", labels: ["phase7"],
    attachments: [],
  },
  {
    id: "em-10", threadId: "t-9", from: { name: "Suresh", email: "suresh@nexus-os.dev" },
    to: [{ name: "Investors", email: "investors@nexus-os.dev" }], subject: "",
    body: "Hi,\n\nQuarterly update draft...",
    bodyHtml: "", timestamp: Date.now() - 600000, read: true, starred: false, folder: "drafts",
    priority: "normal", category: "primary", labels: [],
    attachments: [],
  },
];

/* ─── component ─── */
export default function EmailClient() {
  const [emails, setEmails] = useState<Email[]>(INITIAL_EMAILS);
  const [selectedFolder, setSelectedFolder] = useState<FolderId>("inbox");
  const [selectedEmailId, setSelectedEmailId] = useState<string | null>("em-1");
  const [showCompose, setShowCompose] = useState(false);
  const [showTemplates, setShowTemplates] = useState(false);
  const [searchQuery, setSearchQuery] = useState("");
  const [filterCategory, setFilterCategory] = useState<Category | "all">("all");
  const [sortBy, setSortBy] = useState<"date" | "priority" | "unread">("date");
  const [fuelUsed, setFuelUsed] = useState(52);
  const [auditLog, setAuditLog] = useState<string[]>([
    "Email opened: PR #47 merged",
    "Agent draft created: deployment notification",
    "PII redacted in Research Agent draft",
  ]);

  // compose state
  const [composeTo, setComposeTo] = useState("");
  const [composeSubject, setComposeSubject] = useState("");
  const [composeBody, setComposeBody] = useState("");

  const selectedEmail = useMemo(() => emails.find(e => e.id === selectedEmailId), [emails, selectedEmailId]);

  /* ─── filtered emails ─── */
  const filteredEmails = useMemo(() => {
    let list = emails.filter(e => e.folder === selectedFolder);
    if (filterCategory !== "all") list = list.filter(e => e.category === filterCategory);
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      list = list.filter(e => e.subject.toLowerCase().includes(q) || e.from.name.toLowerCase().includes(q) || e.body.toLowerCase().includes(q));
    }
    list = [...list].sort((a, b) => {
      if (sortBy === "priority") {
        const p: Record<Priority, number> = { high: 0, normal: 1, low: 2 };
        return p[a.priority] - p[b.priority] || b.timestamp - a.timestamp;
      }
      if (sortBy === "unread") return (a.read ? 1 : 0) - (b.read ? 1 : 0) || b.timestamp - a.timestamp;
      return b.timestamp - a.timestamp;
    });
    return list;
  }, [emails, selectedFolder, filterCategory, searchQuery, sortBy]);

  /* ─── thread ─── */
  const thread = useMemo(() => {
    if (!selectedEmail) return [];
    return emails.filter(e => e.threadId === selectedEmail.threadId).sort((a, b) => a.timestamp - b.timestamp);
  }, [emails, selectedEmail]);

  /* ─── counts ─── */
  const folderCounts = useMemo(() => {
    const counts: Record<string, number> = {};
    for (const f of FOLDERS) {
      counts[f.id] = emails.filter(e => e.folder === f.id && !e.read).length;
    }
    return counts;
  }, [emails]);

  /* ─── handlers ─── */
  const markRead = useCallback((id: string) => {
    setEmails(prev => prev.map(e => e.id === id ? { ...e, read: true } : e));
  }, []);

  const toggleStar = useCallback((id: string) => {
    setEmails(prev => prev.map(e => e.id === id ? { ...e, starred: !e.starred } : e));
  }, []);

  const moveToFolder = useCallback((id: string, folder: FolderId) => {
    setEmails(prev => prev.map(e => e.id === id ? { ...e, folder } : e));
    if (selectedEmailId === id) setSelectedEmailId(null);
    logAudit(`Moved email to ${folder}`);
  }, [selectedEmailId]);

  const deleteEmail = useCallback((id: string) => {
    const email = emails.find(e => e.id === id);
    if (email?.folder === "trash") {
      setEmails(prev => prev.filter(e => e.id !== id));
    } else {
      moveToFolder(id, "trash");
    }
    if (selectedEmailId === id) setSelectedEmailId(null);
  }, [emails, selectedEmailId, moveToFolder]);

  const approveAgentDraft = useCallback((id: string) => {
    setEmails(prev => prev.map(e => e.id === id ? { ...e, hitlApproval: "approved", folder: "sent" } : e));
    setFuelUsed(f => f + 8);
    logAudit("HITL approved: agent email sent");
    setSelectedEmailId(null);
  }, []);

  const denyAgentDraft = useCallback((id: string) => {
    setEmails(prev => prev.map(e => e.id === id ? { ...e, hitlApproval: "denied" } : e));
    logAudit("HITL denied: agent email blocked");
  }, []);

  const sendEmail = useCallback(() => {
    if (!composeTo.trim() || !composeSubject.trim()) return;
    const email: Email = {
      id: `em-${Date.now()}`, threadId: `t-${Date.now()}`,
      from: { name: "Suresh", email: "suresh@nexus-os.dev" },
      to: [{ name: composeTo.split("@")[0], email: composeTo }],
      subject: composeSubject, body: composeBody, bodyHtml: "",
      timestamp: Date.now(), read: true, starred: false, folder: "sent",
      priority: "normal", category: "primary", labels: [],
      attachments: [],
    };
    setEmails(prev => [email, ...prev]);
    setComposeTo(""); setComposeSubject(""); setComposeBody("");
    setShowCompose(false);
    setFuelUsed(f => f + 3);
    logAudit(`Email sent to ${composeTo}`);
  }, [composeTo, composeSubject, composeBody]);

  const applyTemplate = useCallback((tmpl: EmailTemplate) => {
    setComposeSubject(tmpl.subject);
    setComposeBody(tmpl.body);
    setShowTemplates(false);
    setFuelUsed(f => f + 2);
    logAudit(`Template applied: ${tmpl.name}`);
  }, []);

  const logAudit = (msg: string) => setAuditLog(prev => [msg, ...prev].slice(0, 20));

  const formatTime = (ts: number) => {
    const diff = Date.now() - ts;
    if (diff < 60000) return "now";
    if (diff < 3600000) return `${Math.floor(diff / 60000)}m`;
    if (diff < 86400000) return `${Math.floor(diff / 3600000)}h`;
    return `${Math.floor(diff / 86400000)}d`;
  };

  const formatDate = (ts: number) => new Date(ts).toLocaleString();

  const formatFileSize = (bytes: number) => {
    if (bytes < 1024) return `${bytes} B`;
    if (bytes < 1048576) return `${(bytes / 1024).toFixed(0)} KB`;
    return `${(bytes / 1048576).toFixed(1)} MB`;
  };

  /* ─── render ─── */
  return (
    <div className="ec-container">
      {/* ─── Sidebar ─── */}
      <aside className="ec-sidebar">
        <div className="ec-sidebar-header">
          <h2 className="ec-sidebar-title">Mail</h2>
          <button className="ec-btn-compose" onClick={() => { setShowCompose(true); setShowTemplates(false); }}>✎ Compose</button>
        </div>

        {/* accounts */}
        <div className="ec-accounts">
          {ACCOUNTS.map(acc => (
            <div key={acc.id} className={`ec-account ${acc.status}`}>
              <span className={`ec-account-icon ec-provider-${acc.provider}`}>{acc.icon}</span>
              <div className="ec-account-info">
                <span className="ec-account-name">{acc.name}</span>
                <span className="ec-account-email">{acc.email}</span>
              </div>
              <span className={`ec-account-dot ec-dot-${acc.status}`}>●</span>
            </div>
          ))}
        </div>

        {/* folders */}
        <div className="ec-folders">
          {FOLDERS.map(folder => (
            <button key={folder.id} className={`ec-folder ${selectedFolder === folder.id ? "active" : ""}`} onClick={() => { setSelectedFolder(folder.id); setSelectedEmailId(null); setFilterCategory("all"); }}>
              <span className="ec-folder-icon">{folder.icon}</span>
              <span className="ec-folder-label">{folder.label}</span>
              {folderCounts[folder.id] > 0 && <span className="ec-folder-badge">{folderCounts[folder.id]}</span>}
            </button>
          ))}
        </div>

        {/* categories */}
        <div className="ec-categories">
          <div className="ec-cat-header">Categories</div>
          {(["all", "primary", "updates", "social", "promotions", "agent"] as const).map(cat => (
            <button key={cat} className={`ec-cat-btn ${filterCategory === cat ? "active" : ""}`} onClick={() => setFilterCategory(cat)}>
              {cat !== "all" && <span className="ec-cat-dot" style={{ background: CATEGORY_COLORS[cat as Category] }} />}
              {cat === "all" ? "All" : cat.charAt(0).toUpperCase() + cat.slice(1)}
            </button>
          ))}
        </div>

        {/* audit */}
        <div className="ec-audit-section">
          <div className="ec-audit-header">Activity</div>
          {auditLog.slice(0, 4).map((msg, i) => (
            <div key={i} className="ec-audit-entry">{msg}</div>
          ))}
        </div>
      </aside>

      {/* ─── Email List ─── */}
      <div className="ec-email-list">
        <div className="ec-list-header">
          <input className="ec-search" placeholder="Search emails..." value={searchQuery} onChange={e => setSearchQuery(e.target.value)} />
          <select className="ec-sort-select" value={sortBy} onChange={e => setSortBy(e.target.value as typeof sortBy)}>
            <option value="date">Date</option>
            <option value="priority">Priority</option>
            <option value="unread">Unread First</option>
          </select>
        </div>
        <div className="ec-list-items">
          {filteredEmails.length === 0 && (
            <div className="ec-empty">
              <div className="ec-empty-icon">📭</div>
              <div>No emails in this folder</div>
            </div>
          )}
          {filteredEmails.map(email => (
            <div key={email.id} className={`ec-email-item ${!email.read ? "unread" : ""} ${selectedEmailId === email.id ? "active" : ""}`} onClick={() => { setSelectedEmailId(email.id); markRead(email.id); }}>
              <div className="ec-email-item-left">
                <button className="ec-star-btn" onClick={e => { e.stopPropagation(); toggleStar(email.id); }}>{email.starred ? "★" : "☆"}</button>
                {email.agentDrafted && <span className="ec-agent-badge" title={`Drafted by ${email.agentDrafted}`}>⬢</span>}
                {email.hitlApproval === "pending" && <span className="ec-hitl-badge">HITL</span>}
              </div>
              <div className="ec-email-item-main">
                <div className="ec-email-from">{email.from.name}</div>
                <div className="ec-email-subject">
                  {email.priority === "high" && <span className="ec-priority-mark">!</span>}
                  {email.subject || "(no subject)"}
                </div>
                <div className="ec-email-snippet">{email.body.slice(0, 80).replace(/\n/g, " ")}...</div>
              </div>
              <div className="ec-email-item-right">
                <span className="ec-email-time">{formatTime(email.timestamp)}</span>
                <span className="ec-email-cat" style={{ background: CATEGORY_COLORS[email.category] + "22", color: CATEGORY_COLORS[email.category] }}>{email.category}</span>
                {email.attachments.length > 0 && <span className="ec-attach-icon">📎</span>}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* ─── Email Detail / Compose ─── */}
      <div className="ec-detail">
        {/* compose */}
        {showCompose && (
          <div className="ec-compose">
            <div className="ec-compose-header">
              <span>New Email</span>
              <div className="ec-compose-actions">
                <button className="ec-btn-template" onClick={() => setShowTemplates(!showTemplates)}>📄 Templates</button>
                <button className="ec-compose-close" onClick={() => setShowCompose(false)}>×</button>
              </div>
            </div>

            {showTemplates && (
              <div className="ec-templates-panel">
                <div className="ec-templates-header">Content Agent Templates</div>
                {TEMPLATES.map(tmpl => (
                  <div key={tmpl.id} className="ec-template-item" onClick={() => applyTemplate(tmpl)}>
                    <div className="ec-template-name">{tmpl.name}</div>
                    <div className="ec-template-meta">⬢ {tmpl.agent} · {tmpl.category}</div>
                  </div>
                ))}
              </div>
            )}

            <div className="ec-compose-fields">
              <div className="ec-compose-field">
                <label>To</label>
                <input value={composeTo} onChange={e => setComposeTo(e.target.value)} placeholder="recipient@example.com" />
              </div>
              <div className="ec-compose-field">
                <label>Subject</label>
                <input value={composeSubject} onChange={e => setComposeSubject(e.target.value)} placeholder="Subject" />
              </div>
            </div>
            <textarea className="ec-compose-body" value={composeBody} onChange={e => setComposeBody(e.target.value)} placeholder="Write your email..." />
            <div className="ec-compose-footer">
              <button className="ec-btn-send" onClick={sendEmail} disabled={!composeTo.trim() || !composeSubject.trim()}>Send</button>
              <button className="ec-btn-draft" onClick={() => { setShowCompose(false); logAudit("Draft saved"); }}>Save Draft</button>
              <span className="ec-compose-fuel">⚡ 3 fuel per send</span>
            </div>
          </div>
        )}

        {/* email detail */}
        {!showCompose && selectedEmail && (
          <div className="ec-email-detail">
            <div className="ec-detail-header">
              <div className="ec-detail-subject-row">
                <h2 className="ec-detail-subject">{selectedEmail.subject || "(no subject)"}</h2>
                {selectedEmail.priority === "high" && <span className="ec-detail-priority">High Priority</span>}
              </div>
              <div className="ec-detail-actions">
                <button className="ec-action-btn" onClick={() => moveToFolder(selectedEmail.id, "archive")} title="Archive">📦</button>
                <button className="ec-action-btn" onClick={() => deleteEmail(selectedEmail.id)} title="Delete">🗑</button>
                <button className="ec-action-btn" onClick={() => toggleStar(selectedEmail.id)} title="Star">{selectedEmail.starred ? "★" : "☆"}</button>
                <button className="ec-action-btn" onClick={() => { setShowCompose(true); setComposeTo(selectedEmail.from.email); setComposeSubject(`Re: ${selectedEmail.subject}`); }} title="Reply">↩</button>
              </div>
            </div>

            {/* labels */}
            {selectedEmail.labels.length > 0 && (
              <div className="ec-detail-labels">
                {selectedEmail.labels.map(label => (
                  <span key={label} className="ec-label">{label}</span>
                ))}
                <span className="ec-label ec-label-cat" style={{ background: CATEGORY_COLORS[selectedEmail.category] + "22", color: CATEGORY_COLORS[selectedEmail.category] }}>{selectedEmail.category}</span>
              </div>
            )}

            {/* PII redaction notice */}
            {selectedEmail.piiRedacted && (
              <div className="ec-pii-notice">
                <span className="ec-pii-icon">🛡</span>
                PII redacted before agent processing. Personal data masked in agent context.
              </div>
            )}

            {/* HITL approval */}
            {selectedEmail.hitlApproval === "pending" && (
              <div className="ec-hitl-panel">
                <div className="ec-hitl-title">⛊ HITL Approval Required</div>
                <div className="ec-hitl-desc">{selectedEmail.agentDrafted} drafted this email and requires your approval before sending.</div>
                <div className="ec-hitl-actions">
                  <button className="ec-hitl-approve" onClick={() => approveAgentDraft(selectedEmail.id)}>✓ Approve & Send</button>
                  <button className="ec-hitl-deny" onClick={() => denyAgentDraft(selectedEmail.id)}>✗ Deny</button>
                </div>
              </div>
            )}

            {selectedEmail.hitlApproval === "denied" && (
              <div className="ec-hitl-denied">
                <span>✗ This agent draft was denied and will not be sent.</span>
              </div>
            )}

            {/* thread */}
            <div className="ec-thread">
              {thread.map(email => (
                <div key={email.id} className={`ec-thread-msg ${email.id === selectedEmail.id ? "current" : ""}`}>
                  <div className="ec-thread-header">
                    <div className="ec-thread-from">
                      <span className="ec-thread-avatar">{email.from.name.charAt(0)}</span>
                      <div className="ec-thread-from-info">
                        <span className="ec-thread-name">{email.from.name}</span>
                        <span className="ec-thread-email">&lt;{email.from.email}&gt;</span>
                      </div>
                    </div>
                    <div className="ec-thread-meta">
                      <span className="ec-thread-date">{formatDate(email.timestamp)}</span>
                      {email.agentDrafted && <span className="ec-thread-agent">⬢ {email.agentDrafted}</span>}
                    </div>
                  </div>
                  <div className="ec-thread-to">
                    To: {email.to.map(t => t.email).join(", ")}
                    {email.cc && email.cc.length > 0 && ` · CC: ${email.cc.map(c => c.email).join(", ")}`}
                  </div>
                  <div className="ec-thread-body">{email.body}</div>
                  {email.attachments.length > 0 && (
                    <div className="ec-thread-attachments">
                      {email.attachments.map((att, i) => (
                        <div key={i} className="ec-attachment">
                          <span className="ec-attach-name">📎 {att.name}</span>
                          <span className="ec-attach-size">{formatFileSize(att.size)}</span>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* no email selected */}
        {!showCompose && !selectedEmail && (
          <div className="ec-no-email">
            <div className="ec-no-email-icon">📧</div>
            <div>Select an email to read</div>
          </div>
        )}
      </div>

      {/* ─── Status Bar ─── */}
      <div className="ec-status-bar">
        <span className="ec-status-item">{FOLDERS.find(f => f.id === selectedFolder)?.label}</span>
        <span className="ec-status-item">{filteredEmails.length} emails</span>
        <span className="ec-status-item">{emails.filter(e => !e.read).length} unread</span>
        <span className="ec-status-item">{emails.filter(e => e.hitlApproval === "pending").length} pending HITL</span>
        <span className="ec-status-item ec-status-right">⚡ {fuelUsed} fuel</span>
        <span className="ec-status-item">{ACCOUNTS.filter(a => a.status === "connected").length}/{ACCOUNTS.length} accounts</span>
      </div>
    </div>
  );
}
