use crate::backend::LoadConfig;
use crate::budget::MemoryBudget;
use crate::error::FlashError;
use crate::profiler::{ModelProfile, PerformanceEstimate};
use crate::types::{HardwareInfo, InferencePreference, InferencePriority};
use nexus_llama_bridge::{GenerationConfig, NumaStrategy};
use serde::{Deserialize, Serialize};

/// Optimal configuration generated by auto-configure.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OptimalConfig {
    pub load_config: LoadConfig,
    pub generation_config: GenerationConfig,
    pub budget: MemoryBudget,
    pub performance_estimate: PerformanceEstimate,
}

/// Generate optimal configuration for given hardware + model.
pub fn auto_configure(
    hw: &HardwareInfo,
    profile: &ModelProfile,
    preference: InferencePreference,
) -> Result<OptimalConfig, FlashError> {
    let target_ctx =
        adjust_context_for_priority(preference.target_context_len, &preference.priority);

    let budget = MemoryBudget::calculate(hw, profile, target_ctx);

    if !budget.is_feasible() {
        // MoE models use mmap to stream expert weights from SSD — only dense
        // weights need to fit in RAM.  llama.cpp handles this internally, so we
        // warn but never block loading.
        tracing::warn!(
            model_min_mb = profile.dense_weight_size_mb + 512,
            available_mb = hw.total_ram_mb,
            "model may be large for available RAM — mmap will stream from disk"
        );
    }

    // Use all available cores — modern llama.cpp scales well on high-core CPUs.
    // Cap at 32 to avoid scheduler overhead on extreme NUMA systems.
    let n_threads = hw.cpu_cores.min(32);
    let n_batch = if profile.is_moe { 512 } else { 2048 }; // Smaller batches for MoE
    let ctx_size = budget
        .max_context_length(profile)
        .min(preference.target_context_len);

    let numa_strategy = if hw.numa_nodes > 1 {
        NumaStrategy::Distribute
    } else {
        NumaStrategy::Disabled
    };

    // Pick a speed-optimized or balanced generation config based on priority,
    // unless the caller provided an explicit override.
    let gen_config = preference
        .generation_config
        .unwrap_or_else(|| match preference.priority {
            InferencePriority::Speed => GenerationConfig::fast(),
            _ => GenerationConfig::balanced(),
        });

    let load_config = LoadConfig {
        model_path: preference.model_path,
        n_gpu_layers: 0,  // CPU only by default
        use_mmap: true,   // Essential for disk streaming
        use_mlock: false, // Don't pin — let OS manage
        cpu_moe: profile.is_moe,
        n_threads: Some(n_threads),
        numa_strategy,
        n_ctx: ctx_size,
        n_batch,
    };

    let generation_config = GenerationConfig {
        n_ctx: ctx_size,
        n_batch,
        n_threads: Some(n_threads),
        ..gen_config
    };

    let performance_estimate = profile.estimate_performance(hw, &budget);

    Ok(OptimalConfig {
        load_config,
        generation_config,
        budget,
        performance_estimate,
    })
}

fn adjust_context_for_priority(target: u32, priority: &InferencePriority) -> u32 {
    match priority {
        InferencePriority::Speed => target.min(2048), // Smaller KV cache = faster
        InferencePriority::Context => target,
        InferencePriority::Balanced => target.min(4096),
    }
}
