use crate::backend::LoadConfig;
use crate::budget::MemoryBudget;
use crate::error::FlashError;
use crate::profiler::{ModelProfile, PerformanceEstimate};
use crate::types::{HardwareInfo, InferencePreference, InferencePriority};
use nexus_llama_bridge::{GenerationConfig, NumaStrategy};
use serde::{Deserialize, Serialize};

/// Optimal configuration generated by auto-configure.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct OptimalConfig {
    pub load_config: LoadConfig,
    pub generation_config: GenerationConfig,
    pub budget: MemoryBudget,
    pub performance_estimate: PerformanceEstimate,
}

/// Generate optimal configuration for given hardware + model.
pub fn auto_configure(
    hw: &HardwareInfo,
    profile: &ModelProfile,
    preference: InferencePreference,
) -> Result<OptimalConfig, FlashError> {
    let target_ctx =
        adjust_context_for_priority(preference.target_context_len, &preference.priority);

    let budget = MemoryBudget::calculate(hw, profile, target_ctx);

    if !budget.is_feasible() {
        return Err(FlashError::ModelTooLarge {
            model_min_mb: profile.dense_weight_size_mb + 512,
            available_mb: hw.total_ram_mb,
            suggestion: suggest_smaller_model(profile, hw),
        });
    }

    let n_threads = hw.cpu_cores.min(16); // Diminishing returns above 16
    let n_batch = if profile.is_moe { 512 } else { 2048 }; // Smaller batches for MoE
    let ctx_size = budget
        .max_context_length(profile)
        .min(preference.target_context_len);

    let numa_strategy = if hw.numa_nodes > 1 {
        NumaStrategy::Distribute
    } else {
        NumaStrategy::Disabled
    };

    let gen_config = preference.generation_config.unwrap_or_default();

    let load_config = LoadConfig {
        model_path: preference.model_path,
        n_gpu_layers: 0,  // CPU only by default
        use_mmap: true,   // Essential for disk streaming
        use_mlock: false, // Don't pin — let OS manage
        cpu_moe: profile.is_moe,
        n_threads: Some(n_threads),
        numa_strategy,
        n_ctx: ctx_size,
        n_batch,
    };

    let generation_config = GenerationConfig {
        n_ctx: ctx_size,
        n_batch,
        ..gen_config
    };

    let performance_estimate = profile.estimate_performance(hw, &budget);

    Ok(OptimalConfig {
        load_config,
        generation_config,
        budget,
        performance_estimate,
    })
}

/// Suggest a smaller model when the requested one doesn't fit.
pub fn suggest_smaller_model(profile: &ModelProfile, hw: &HardwareInfo) -> String {
    let available_gb = hw.total_ram_mb as f64 / 1024.0;

    if available_gb < 4.0 {
        format!(
            "With {:.0}GB RAM, try a 1-3B parameter model (e.g., Qwen3-1.7B, Gemma-3-1B)",
            available_gb
        )
    } else if available_gb < 8.0 {
        format!(
            "With {:.0}GB RAM, try a 3-7B parameter model (e.g., Qwen3-4B, Llama-3.1-8B Q4)",
            available_gb
        )
    } else if available_gb < 16.0 {
        format!(
            "With {:.0}GB RAM, try a 7-14B parameter model (e.g., Qwen3-8B, Phi-4-14B)",
            available_gb
        )
    } else if available_gb < 32.0 {
        format!(
            "With {:.0}GB RAM, try a 14-32B parameter model or MoE (e.g., Qwen3-32B Q4, Qwen3.5-35B-A3B)",
            available_gb
        )
    } else {
        format!(
            "Model {} ({:.0}GB) is too large. With {:.0}GB RAM, try a smaller quantization or model variant",
            profile.name, profile.file_size_mb as f64 / 1024.0, available_gb
        )
    }
}

fn adjust_context_for_priority(target: u32, priority: &InferencePriority) -> u32 {
    match priority {
        InferencePriority::Speed => target.min(4096),
        InferencePriority::Context => target,
        InferencePriority::Balanced => target,
    }
}
