import { describe, it, expect } from 'vitest';

const pages = [
  'ABValidation',
  'AdminCompliance',
  'AdminDashboard',
  'AdminFleet',
  'AdminPolicyEditor',
  'AdminSystemHealth',
  'AdminUsers',
  'AgentBrowser',
  'AgentDnaLab',
  'AgentMemory',
  'Agents',
  'AiChatHub',
  'ApiClient',
  'AppStore',
  'ApprovalCenter',
  'Audit',
  'AuditTimeline',
  'BrowserAgent',
  'CapabilityBoundaryMap',
  'Chat',
  'Civilization',
  'ClusterStatus',
  'CodeEditor',
  'Collaboration',
  'CommandCenter',
  'commandCenterUi',
  'ComplianceDashboard',
  'ComputerControl',
  'ConsciousnessMonitor',
  'Dashboard',
  'DatabaseManager',
  'DeployPipeline',
  'DesignStudio',
  'DeveloperPortal',
  'DistributedAudit',
  'Documents',
  'DreamForge',
  'EmailClient',
  'ExternalTools',
  'FileManager',
  'Firewall',
  'FlashInference',
  'GovernanceOracle',
  'GovernedControl',
  'Identity',
  'ImmuneDashboard',
  'Integrations',
  'KnowledgeGraph',
  'LearningCenter',
  'Login',
  'MeasurementBatteries',
  'MeasurementCompare',
  'MeasurementDashboard',
  'MeasurementSession',
  'MediaStudio',
  'Memory',
  'Messaging',
  'MissionControl',
  'ModelHub',
  'ModelRouting',
  'NotesApp',
  'Perception',
  'PermissionDashboard',
  'PolicyManagement',
  'ProjectManager',
  'Protocols',
  'Scheduler',
  'SelfRewriteLab',
  'Settings',
  'SetupWizard',
  'SoftwareFactory',
  'SystemMonitor',
  'Telemetry',
  'TemporalEngine',
  'Terminal',
  'TimeMachine',
  'TimelineViewer',
  'TokenEconomy',
  'TrustDashboard',
  'UsageBilling',
  'VoiceAssistant',
  'Workflows',
  'Workspaces',
  'WorldSimulation',
  'WorldSimulation2',
];

describe('Page modules', () => {
  it.each(pages)('%s exports a component (default or named)', async (page) => {
    const mod = await import(`../pages/${page}.tsx`);
    // Accept either default export or any named export that is a function/component
    const hasDefault = mod.default !== undefined;
    const hasNamed = Object.keys(mod).some(
      (key) => key !== 'default' && typeof mod[key] === 'function',
    );
    expect(hasDefault || hasNamed).toBe(true);
  });
});
