use serde::{Deserialize, Serialize};
use uuid::Uuid;

// ── Improvement Domain ──────────────────────────────────────────────

/// What aspect of the system can be improved.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum ImprovementDomain {
    /// DSPy-style prompt improvement (Phase 3).
    PromptOptimization,
    /// Runtime config optimization (Phase 3).
    ConfigTuning,
    /// DRL-based scheduling improvement (Phase 4).
    SchedulingPolicy,
    /// Predictive router improvement (Phase 4).
    RoutingStrategy,
    /// Cedar policy refinement — NOT kernel modification (Phase 3).
    GovernancePolicy,
    /// Actual code modification — future, feature-gated (Phase 5).
    CodePatch,
}

// ── Improvement Status (lifecycle) ──────────────────────────────────

/// Lifecycle state of an improvement from detection through deployment.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ImprovementStatus {
    /// Signal detected by the Observer.
    Observed,
    /// Opportunity identified and prioritized by the Analyzer.
    Analyzed,
    /// Concrete change generated by the Proposer.
    Proposed,
    /// Passed all checks + HITL approved by the Validator.
    Validated,
    /// Change deployed with checkpoint by the Applier.
    Applied,
    /// In canary monitoring period.
    Monitoring,
    /// Canary passed, change permanent.
    Committed,
    /// Canary failed, reverted.
    RolledBack,
    /// Validator or HITL rejected.
    Rejected,
}

// ── Signal (Observer output) ────────────────────────────────────────

/// Which subsystem detected the improvement signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SignalSource {
    /// OWASP #10 anomaly detection.
    AnomalyMonitor,
    /// CPU/memory/latency monitoring.
    PerformanceProfiler,
    /// Test failure patterns.
    TestSuite,
    /// Audit anomalies.
    AuditTrail,
    /// Explicit user signals.
    UserFeedback,
    /// Agent capability score trends.
    CapabilityMeasurement,
}

/// A piece of evidence supporting a signal.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EvidenceItem {
    pub timestamp: u64,
    pub description: String,
    pub data: serde_json::Value,
}

/// A signal emitted by the Observer when a metric deviates from baseline.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImprovementSignal {
    pub id: Uuid,
    pub timestamp: u64,
    pub domain: ImprovementDomain,
    pub source: SignalSource,
    pub metric_name: String,
    pub current_value: f64,
    pub baseline_value: f64,
    /// How many standard deviations from baseline.
    pub deviation_sigma: f64,
    pub evidence: Vec<EvidenceItem>,
}

// ── Opportunity (Analyzer output) ───────────────────────────────────

/// Classification of what kind of improvement this is.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OpportunityClass {
    /// Speed, throughput, resource usage.
    Performance,
    /// Vulnerability, policy gap.
    Security,
    /// Code quality, error handling.
    Quality,
    /// Missing capability.
    FeatureGap,
    /// Crash prevention, error recovery.
    Reliability,
}

/// How severe the issue is.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum Severity {
    Low,
    Medium,
    High,
    Critical,
}

/// How much of the system is affected by the change.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub enum BlastRadius {
    /// Single agent affected.
    Agent,
    /// Multiple agents or one subsystem.
    Subsystem,
    /// Platform-wide change.
    Platform,
}

/// An improvement opportunity identified by the Analyzer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImprovementOpportunity {
    pub id: Uuid,
    pub signal_ids: Vec<Uuid>,
    pub domain: ImprovementDomain,
    pub classification: OpportunityClass,
    pub severity: Severity,
    pub blast_radius: BlastRadius,
    /// 0.0–1.0: how confident we are this is a real opportunity.
    pub confidence: f64,
    /// Expected improvement magnitude.
    pub estimated_impact: f64,
}

// ── Proposal (Proposer output) ──────────────────────────────────────

/// A variant tried during prompt optimization.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PromptVariant {
    pub variant_id: Uuid,
    pub prompt_text: String,
    pub score: f64,
}

/// The concrete change to be applied.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum ProposedChange {
    PromptUpdate {
        agent_id: String,
        old_prompt_hash: String,
        new_prompt: String,
        optimization_trajectory: Vec<PromptVariant>,
    },
    ConfigChange {
        key: String,
        old_value: serde_json::Value,
        new_value: serde_json::Value,
        justification: String,
    },
    PolicyUpdate {
        policy_id: String,
        old_policy_hash: String,
        new_policy_cedar: String,
    },
    SchedulingUpdate {
        old_weights: Vec<f64>,
        new_weights: Vec<f64>,
        training_episodes: u32,
    },
    CodePatch {
        target_file: String,
        diff: String,
        proof: SafetyProof,
    },
}

impl ProposedChange {
    /// Returns the domain of this change.
    pub fn domain(&self) -> ImprovementDomain {
        match self {
            Self::PromptUpdate { .. } => ImprovementDomain::PromptOptimization,
            Self::ConfigChange { .. } => ImprovementDomain::ConfigTuning,
            Self::PolicyUpdate { .. } => ImprovementDomain::GovernancePolicy,
            Self::SchedulingUpdate { .. } => ImprovementDomain::SchedulingPolicy,
            Self::CodePatch { .. } => ImprovementDomain::CodePatch,
        }
    }

    /// Returns files touched by this change (for invariant checking).
    pub fn touched_files(&self) -> Vec<&str> {
        match self {
            Self::CodePatch { target_file, .. } => vec![target_file.as_str()],
            _ => vec![],
        }
    }
}

/// Identifier for a hard invariant.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct InvariantId(pub u8);

/// Proof that a change is safe.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SafetyProof {
    pub invariants_checked: Vec<InvariantId>,
    pub proof_method: ProofMethod,
    pub verifier_version: String,
    pub proof_hash: String,
}

/// How the safety proof was generated.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ProofMethod {
    /// Rust compiler verification.
    TypeCheck,
    /// No clippy warnings.
    ClippyClean,
    /// All existing tests pass.
    TestSuitePassed,
    /// Kani/Prusti formal proof.
    FormalVerification,
    /// Runtime metrics within bounds.
    BehavioralEnvelope,
    /// Multiple verification methods combined.
    MultiOracle,
}

/// A step in the rollback plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RollbackStep {
    pub description: String,
    pub action: serde_json::Value,
}

/// Plan for reverting a change.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RollbackPlan {
    pub checkpoint_id: Uuid,
    pub steps: Vec<RollbackStep>,
    pub estimated_rollback_time_ms: u64,
    pub automatic: bool,
}

/// A concrete improvement proposal generated by the Proposer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ImprovementProposal {
    pub id: Uuid,
    pub opportunity_id: Uuid,
    pub domain: ImprovementDomain,
    pub description: String,
    pub change: ProposedChange,
    pub rollback_plan: RollbackPlan,
    pub expected_tests: Vec<String>,
    pub proof: Option<SafetyProof>,
    pub generated_by: String,
    pub fuel_cost: u64,
}

// ── Validated Proposal (Validator output) ───────────────────────────

/// A proposal that has passed all validation checks including HITL.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ValidatedProposal {
    pub proposal: ImprovementProposal,
    pub validation_timestamp: u64,
    pub invariants_passed: usize,
    pub tests_passed: usize,
    pub simulation_risk_score: f64,
    pub hitl_signature: String,
}

// ── Applied Improvement (Applier output) ────────────────────────────

/// An improvement that has been applied and is in canary monitoring.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppliedImprovement {
    pub id: Uuid,
    pub proposal_id: Uuid,
    pub checkpoint_id: Uuid,
    pub applied_at: u64,
    pub status: ImprovementStatus,
    pub canary_deadline: u64,
}

// ── System State (input to the pipeline) ────────────────────────────

/// Rolling metric baseline for anomaly detection.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MetricBaseline {
    pub mean: f64,
    pub std_dev: f64,
    pub sample_count: u64,
}

/// Snapshot of system metrics for the Observer.
#[derive(Debug, Clone, Default)]
pub struct SystemMetrics {
    pub metrics: Vec<(String, f64)>,
}

impl SystemMetrics {
    pub fn new() -> Self {
        Self {
            metrics: Vec::new(),
        }
    }

    pub fn insert(&mut self, name: impl Into<String>, value: f64) {
        self.metrics.push((name.into(), value));
    }

    pub fn iter(&self) -> impl Iterator<Item = (&str, &f64)> {
        self.metrics.iter().map(|(k, v)| (k.as_str(), v))
    }
}

/// Context available to the Proposer for generating changes.
#[derive(Debug, Clone, Default)]
pub struct SystemContext {
    pub agent_configs: serde_json::Value,
    pub current_policies: serde_json::Value,
    pub recent_audit_summary: String,
}

/// Full system state passed into the pipeline.
#[derive(Debug, Clone)]
pub struct SystemState {
    pub metrics: SystemMetrics,
    pub context: SystemContext,
    pub audit_chain_valid: bool,
    pub test_suite_passing: bool,
}

// ── Cycle Result ────────────────────────────────────────────────────

/// Result of a single pipeline cycle.
#[derive(Debug)]
pub enum CycleResult {
    /// No signals detected — system is healthy.
    NoSignals,
    /// Signals detected but no actionable opportunities.
    NoOpportunities,
    /// Proposal generation failed.
    ProposalFailed(String),
    /// Validation failed (invariant violation, test failure, HITL denial).
    ValidationFailed(String),
    /// Application failed (checkpoint or test failure post-apply).
    ApplyFailed(String),
    /// Improvement successfully applied and entering canary period.
    Applied(AppliedImprovement),
}
