use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::agent::action::{ActionPlan, ActionResult};
use crate::error::ComputerUseError;

/// Maximum allowed max_steps value (hard safety limit)
const ABSOLUTE_MAX_STEPS: u32 = 100;

/// Record of a single step in the agent's execution
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StepRecord {
    /// Step number (1-indexed)
    pub step: u32,
    /// The plan generated by the vision model
    pub plan: ActionPlan,
    /// Results of executing each action in the plan
    pub results: Vec<ActionResult>,
    /// Whether the user approved this step (true if auto-mode)
    pub user_approved: bool,
    /// Timestamp when the step started
    pub timestamp: DateTime<Utc>,
    /// Hash of this step for audit trail
    pub audit_hash: String,
}

impl StepRecord {
    /// Create a new step record
    pub fn new(step: u32, plan: ActionPlan, user_approved: bool) -> Self {
        let audit_hash = compute_step_hash(step, &plan);
        Self {
            step,
            plan,
            results: Vec::new(),
            user_approved,
            timestamp: Utc::now(),
            audit_hash,
        }
    }

    /// Add an action result to this step
    pub fn add_result(&mut self, result: ActionResult) {
        self.results.push(result);
    }

    /// Generate a summary string for this step (used in history context)
    pub fn summary(&self) -> String {
        let actions: Vec<String> = self.plan.actions.iter().map(|a| a.to_string()).collect();
        let success_count = self.results.iter().filter(|r| r.success).count();
        let total = self.results.len();
        format!(
            "Actions: [{}] — {success_count}/{total} succeeded",
            actions.join(", ")
        )
    }
}

/// Compute a hash for a step record
fn compute_step_hash(step: u32, plan: &ActionPlan) -> String {
    let mut hasher = Sha256::new();
    hasher.update(step.to_le_bytes());
    hasher.update(plan.observation.as_bytes());
    hasher.update(plan.reasoning.as_bytes());
    hasher.update(Utc::now().to_rfc3339().as_bytes());
    hex::encode(hasher.finalize())
}

/// Step planner that tracks execution history and enforces max steps
pub struct StepPlanner {
    /// Maximum number of steps allowed
    max_steps: u32,
    /// All step records
    history: Vec<StepRecord>,
}

impl StepPlanner {
    /// Create a new StepPlanner with the given max steps
    pub fn new(max_steps: u32) -> Self {
        // Clamp to absolute max
        let max_steps = max_steps.min(ABSOLUTE_MAX_STEPS);
        Self {
            max_steps,
            history: Vec::new(),
        }
    }

    /// Get the current step number (1-indexed, next step to execute)
    pub fn current_step(&self) -> u32 {
        self.history.len() as u32 + 1
    }

    /// Check if we've exceeded the max step limit
    pub fn is_at_limit(&self) -> bool {
        self.history.len() as u32 >= self.max_steps
    }

    /// Get the max steps limit
    pub fn max_steps(&self) -> u32 {
        self.max_steps
    }

    /// Add a completed step to the history
    pub fn add_step(&mut self, record: StepRecord) -> Result<(), ComputerUseError> {
        if self.is_at_limit() {
            return Err(ComputerUseError::MaxStepsExceeded {
                max_steps: self.max_steps,
            });
        }
        self.history.push(record);
        Ok(())
    }

    /// Get the history as summary strings for vision context
    pub fn history_context(&self) -> Vec<String> {
        self.history.iter().map(|s| s.summary()).collect()
    }

    /// Get a reference to the full history
    pub fn history(&self) -> &[StepRecord] {
        &self.history
    }

    /// Total fuel consumed across all steps
    pub fn total_fuel(&self) -> u64 {
        self.history
            .iter()
            .flat_map(|s| &s.results)
            .map(|r| if r.success { 1u64 } else { 0u64 })
            .sum()
    }

    /// Total duration across all steps in milliseconds
    pub fn total_duration_ms(&self) -> u64 {
        self.history
            .iter()
            .flat_map(|s| &s.results)
            .map(|r| r.duration_ms)
            .sum()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::agent::action::AgentAction;

    fn make_plan(actions: Vec<AgentAction>) -> ActionPlan {
        ActionPlan {
            observation: "test observation".to_string(),
            reasoning: "test reasoning".to_string(),
            actions,
            confidence: 0.9,
        }
    }

    #[test]
    fn test_planner_creation() {
        let planner = StepPlanner::new(10);
        assert_eq!(planner.max_steps(), 10);
        assert_eq!(planner.current_step(), 1);
        assert!(!planner.is_at_limit());
        assert!(planner.history().is_empty());
    }

    #[test]
    fn test_planner_add_step() {
        let mut planner = StepPlanner::new(10);
        let plan = make_plan(vec![AgentAction::Click {
            x: 100,
            y: 200,
            button: "left".to_string(),
        }]);
        let record = StepRecord::new(1, plan, true);
        planner.add_step(record).expect("add step");
        assert_eq!(planner.current_step(), 2);
        assert_eq!(planner.history().len(), 1);
    }

    #[test]
    fn test_planner_max_steps_enforced() {
        let mut planner = StepPlanner::new(2);
        for i in 0..2 {
            let plan = make_plan(vec![]);
            let record = StepRecord::new(i + 1, plan, true);
            planner.add_step(record).expect("add step");
        }
        assert!(planner.is_at_limit());

        let plan = make_plan(vec![]);
        let record = StepRecord::new(3, plan, true);
        let result = planner.add_step(record);
        assert!(result.is_err());
        assert!(matches!(
            result.unwrap_err(),
            ComputerUseError::MaxStepsExceeded { max_steps: 2 }
        ));
    }

    #[test]
    fn test_planner_max_steps_clamped_to_100() {
        let planner = StepPlanner::new(500);
        assert_eq!(planner.max_steps(), ABSOLUTE_MAX_STEPS);
    }

    #[test]
    fn test_planner_history_context_generation() {
        let mut planner = StepPlanner::new(10);

        let plan = make_plan(vec![
            AgentAction::Click {
                x: 100,
                y: 200,
                button: "left".to_string(),
            },
            AgentAction::Type {
                text: "hello".to_string(),
            },
        ]);
        let mut record = StepRecord::new(1, plan, true);
        record.add_result(ActionResult::success("click(left, 100, 200)", 50));
        record.add_result(ActionResult::success("type(hello)", 30));
        planner.add_step(record).expect("add");

        let context = planner.history_context();
        assert_eq!(context.len(), 1);
        assert!(context[0].contains("click(left, 100, 200)"));
        assert!(context[0].contains("2/2 succeeded"));
    }

    #[test]
    fn test_planner_step_record_creation() {
        let plan = make_plan(vec![AgentAction::Screenshot]);
        let record = StepRecord::new(1, plan, false);
        assert_eq!(record.step, 1);
        assert!(!record.user_approved);
        assert_eq!(record.audit_hash.len(), 64);
        assert!(record.results.is_empty());
    }

    #[test]
    fn test_planner_empty_history() {
        let planner = StepPlanner::new(10);
        assert!(planner.history_context().is_empty());
        assert_eq!(planner.total_fuel(), 0);
        assert_eq!(planner.total_duration_ms(), 0);
    }

    #[test]
    fn test_planner_total_fuel_calculation() {
        let mut planner = StepPlanner::new(10);
        let plan = make_plan(vec![]);
        let mut record = StepRecord::new(1, plan, true);
        record.add_result(ActionResult::success("click", 10));
        record.add_result(ActionResult::success("type", 20));
        record.add_result(ActionResult::failure("scroll", "err", 5));
        planner.add_step(record).expect("add");

        // 2 successful = 2 fuel
        assert_eq!(planner.total_fuel(), 2);
        // total duration = 10 + 20 + 5
        assert_eq!(planner.total_duration_ms(), 35);
    }

    #[test]
    fn test_step_record_summary() {
        let plan = make_plan(vec![AgentAction::Click {
            x: 10,
            y: 20,
            button: "left".to_string(),
        }]);
        let mut record = StepRecord::new(1, plan, true);
        record.add_result(ActionResult::success("click(left, 10, 20)", 42));
        let summary = record.summary();
        assert!(summary.contains("click(left, 10, 20)"));
        assert!(summary.contains("1/1 succeeded"));
    }
}
