use super::*;

const MANIFEST: &str = r#"# A dependency-free library.
[package]
name = "answer"
version = "0.1.0"
edition = "2021"
authors = ["A. Person <a@example.invalid>"]
description = 'Answers, with a # inside'
publish = false

[dependencies]
"#;

const LOCK: &str = "# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = \"answer\"
version = \"0.1.0\"
";

fn candidate(files: &[(&str, &str)]) -> Result<RustPackage, NotApplicable> {
    let map: BTreeMap<String, String> = files
        .iter()
        .map(|(path, text)| (path.to_string(), text.to_string()))
        .collect();
    let paths: BTreeSet<String> = map.keys().cloned().collect();
    check(&paths, &|path| {
        map.get(path).map(|text| text.as_bytes().to_vec())
    })
}

fn with_manifest(manifest: &str) -> Result<RustPackage, NotApplicable> {
    candidate(&[
        ("Cargo.toml", manifest),
        ("Cargo.lock", LOCK),
        ("src/lib.rs", "pub fn answer() -> u32 { 42 }"),
    ])
}

#[test]
fn p2g_a_dependency_free_library_is_applicable() {
    assert_eq!(
        with_manifest(MANIFEST),
        Ok(RustPackage {
            name: "answer".into(),
            version: "0.1.0".into(),
        })
    );
    // Tests, benches and binaries may sit beside the library.
    assert!(candidate(&[
        ("Cargo.toml", MANIFEST),
        ("Cargo.lock", LOCK),
        ("src/lib.rs", ""),
        ("src/main.rs", ""),
        ("tests/it.rs", ""),
        ("README.md", ""),
    ])
    .is_ok());
    // The accepted [lib] keys; the lock format may be 3.
    let lib = format!("{MANIFEST}\n[lib]\nname = \"answer\"\npath = \"src/core.rs\"\ntest = true\ndoctest = false\n");
    assert!(candidate(&[
        ("Cargo.toml", &lib),
        ("Cargo.lock", &LOCK.replace("version = 4", "version = 3")),
        ("src/core.rs", ""),
    ])
    .is_ok());
    // Multi-line arrays and comments.
    let arrays = MANIFEST.replace(
        "authors = [\"A. Person <a@example.invalid>\"]",
        "authors = [\n  \"One\", # first\n  \"Two\",\n]\nkeywords = []",
    );
    assert!(with_manifest(&arrays).is_ok());
}

#[test]
fn p2g_every_dependency_kind_is_refused() {
    use NotApplicable::*;
    for (table, reason) in [
        ("[dependencies]\nserde = \"1\"", Dependencies),
        (
            "[dependencies]\nlocal = { path = \"../local\" }",
            Dependencies,
        ),
        (
            "[dependencies]\nremote = { git = \"https://example.invalid/r\" }",
            Dependencies,
        ),
        ("[dependencies.serde]\nversion = \"1\"", Dependencies),
        ("[dev-dependencies]\nquickcheck = \"1\"", DevDependencies),
        ("[dev-dependencies]", DevDependencies),
        ("[build-dependencies]\ncc = \"1\"", BuildDependencies),
        (
            "[target.x86_64-unknown-linux-gnu.dependencies]\nlibc = \"0.2\"",
            TargetSpecific,
        ),
        (
            "[target.'cfg(unix)'.dependencies]\nlibc = \"0.2\"",
            TargetSpecific,
        ),
        ("[patch.crates-io]\nserde = { path = \"x\" }", Patch),
        ("[replace]\n\"serde:1.0.0\" = { path = \"x\" }", Patch),
        ("[workspace]\nmembers = [\"a\"]", Workspace),
    ] {
        let manifest = MANIFEST.replace("[dependencies]\n", table);
        assert_eq!(with_manifest(&manifest), Err(reason), "{table}");
    }
}

#[test]
fn p2g_build_scripts_config_and_other_settings_are_refused() {
    use NotApplicable::*;
    let files = |extra: (&str, &str)| {
        candidate(&[
            ("Cargo.toml", MANIFEST),
            ("Cargo.lock", LOCK),
            ("src/lib.rs", ""),
            extra,
        ])
    };
    assert_eq!(files(("build.rs", "fn main() {}")), Err(BuildScript));
    assert_eq!(files((".cargo/config.toml", "")), Err(CargoConfig));
    assert_eq!(files((".cargo/config", "")), Err(CargoConfig));
    assert_eq!(files(("sub/.cargo/config.toml", "")), Err(CargoConfig));
    for (key, reason) in [
        ("build = \"gen.rs\"", BuildScript),
        ("links = \"z\"", BuildScript),
        ("workspace = \"..\"", Workspace),
        ("resolver = \"2\"", UnsupportedSetting),
        ("autotests = false", UnsupportedSetting),
        ("default-run = \"x\"", UnsupportedSetting),
    ] {
        let manifest = MANIFEST.replace("publish = false", key);
        assert_eq!(with_manifest(&manifest), Err(reason), "{key}");
    }
    for (table, reason) in [
        ("[lib]\nproc-macro = true", NotALibrary),
        ("[lib]\ncrate-type = [\"cdylib\"]", NotALibrary),
        ("[lib]\nharness = false", UnsupportedSetting),
        ("[lib]\npath = \"../outside.rs\"", UnsupportedManifest),
        ("[features]\ndefault = []", UnsupportedSetting),
        ("[profile.test]\nopt-level = 3", UnsupportedSetting),
        ("[[bin]]\nname = \"x\"", UnsupportedSetting),
        (
            "[[test]]\nname = \"x\"\nharness = false",
            UnsupportedSetting,
        ),
        (
            "[package.metadata.docs.rs]\nall-features = true",
            UnsupportedSetting,
        ),
        ("[lints.rust]\nunsafe_code = \"forbid\"", UnsupportedSetting),
    ] {
        let manifest = format!("{MANIFEST}\n{table}\n");
        assert_eq!(with_manifest(&manifest), Err(reason), "{table}");
    }
    let top = format!("cargo-features = [\"x\"]\n{MANIFEST}");
    assert_eq!(with_manifest(&top), Err(UnsupportedSetting));
}

#[test]
fn p2g_the_manifest_grammar_is_exact() {
    use NotApplicable::*;
    for manifest in [
        // Outside the subset.
        "[package]\nname = \"answer\"\nversion = \"0.1.0\"\ndescription = \"\"\"multi\"\"\"\n",
        "[package]\nname = \"answer\"\nversion = \"0.1.0\"\npackage.edition = \"2021\"\n",
        "[package]\nname = \"answer\"\nversion = \"0.1.0\"\nedition = 2021\n",
        "[package]\nname = \"answer\"\nversion = \"0.1.0\"\nedition = \"2022\"\n",
        "[package]\nname = \"answer\"\nversion = \"0.1\"\n",
        "[package]\nname = \"1answer\"\nversion = \"0.1.0\"\n",
        "[package]\nname = \"answer\"\n",
        "[package]\nname = \"answer\"\nname = \"again\"\nversion = \"0.1.0\"\n",
        "[package]\nname = \"answer\"\nversion = \"0.1.0\"\n[package]\n",
        "[package]\nname = \"answer\nversion = \"0.1.0\"\n",
        "name = \"answer\"\n",
        "",
    ] {
        let result = with_manifest(manifest);
        assert!(
            matches!(result, Err(UnsupportedManifest | UnsupportedSetting)),
            "{manifest:?}: {result:?}"
        );
    }
    assert_eq!(
        candidate(&[("Cargo.lock", LOCK), ("src/lib.rs", "")]),
        Err(NoManifest)
    );
    assert_eq!(
        candidate(&[
            ("Cargo.toml", "\u{0}"),
            ("Cargo.lock", LOCK),
            ("src/lib.rs", "")
        ]),
        Err(UnsupportedManifest)
    );
}

#[test]
fn p2g_the_library_and_a_current_lock_file_are_required() {
    use NotApplicable::*;
    assert_eq!(
        candidate(&[("Cargo.toml", MANIFEST), ("Cargo.lock", LOCK)]),
        Err(MissingLibrary)
    );
    assert_eq!(
        candidate(&[("Cargo.toml", MANIFEST), ("src/lib.rs", "")]),
        Err(MissingLockFile)
    );
    for lock in [
        LOCK.replace("name = \"answer\"", "name = \"other\""),
        LOCK.replace("version = \"0.1.0\"", "version = \"0.2.0\""),
        LOCK.replace("version = 4", "version = 2"),
        LOCK.replace("version = 4\n", ""),
        format!("{LOCK}source = \"registry+https://github.com/rust-lang/crates.io-index\"\n"),
        format!("{LOCK}checksum = \"00\"\n"),
        format!("{LOCK}dependencies = [\"serde\"]\n"),
        format!("{LOCK}\n[[package]]\nname = \"serde\"\nversion = \"1.0.0\"\n"),
        String::new(),
    ] {
        assert_eq!(
            candidate(&[
                ("Cargo.toml", MANIFEST),
                ("Cargo.lock", &lock),
                ("src/lib.rs", "")
            ]),
            Err(StaleLockFile),
            "{lock:?}"
        );
    }
}
