//! ProactiveAssistant — suggest and execute actions before the user asks.

use super::intent::{ConfidenceLevel, IntentPrediction};
use super::OmniscienceError;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::time::{SystemTime, UNIX_EPOCH};
use uuid::Uuid;

// ── Types ───────────────────────────────────────────────────────────────

/// How prominently to display suggestions to the user.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum NotificationStyle {
    /// No visible notification; logged only.
    Silent,
    /// Small, unobtrusive indicator.
    Subtle,
    /// Standard notification popup.
    Normal,
    /// Large, attention-grabbing notification.
    Prominent,
}

/// Lifecycle status of a suggestion.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum SuggestionStatus {
    /// Queued for display.
    Queued,
    /// Currently shown to the user.
    Shown,
    /// User accepted the suggestion.
    Accepted,
    /// User dismissed the suggestion.
    Dismissed,
    /// Suggestion expired without user action.
    Expired,
}

/// A proactive suggestion generated by the assistant.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Suggestion {
    /// Unique identifier.
    pub id: Uuid,
    /// The predicted intent that triggered this suggestion.
    pub intent: String,
    /// The suggested action to take.
    pub action: String,
    /// Confidence level of the underlying prediction.
    pub confidence: ConfidenceLevel,
    /// Current lifecycle status.
    pub status: SuggestionStatus,
    /// Unix timestamp in milliseconds when created.
    pub created_at: u64,
}

/// Configuration for the proactive assistant.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AssistanceConfig {
    /// Whether proactive suggestions are enabled.
    pub enable_proactive: bool,
    /// Minimum confidence score to generate a suggestion.
    pub min_confidence: f64,
    /// How to display suggestions.
    pub notification_style: NotificationStyle,
    /// Maximum number of active (non-terminal) suggestions.
    pub max_active_suggestions: usize,
    /// Expiry time in milliseconds for unacknowledged suggestions.
    pub suggestion_expiry_ms: u64,
}

impl Default for AssistanceConfig {
    fn default() -> Self {
        Self {
            enable_proactive: true,
            min_confidence: 0.5,
            notification_style: NotificationStyle::Subtle,
            max_active_suggestions: 5,
            suggestion_expiry_ms: 60_000,
        }
    }
}

// ── ProactiveAssistant ──────────────────────────────────────────────────

/// Proactive assistant that generates, tracks, and manages suggestions.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ProactiveAssistant {
    config: AssistanceConfig,
    suggestions: HashMap<Uuid, Suggestion>,
}

impl ProactiveAssistant {
    /// Create a new assistant with default configuration.
    pub fn new() -> Self {
        Self {
            config: AssistanceConfig::default(),
            suggestions: HashMap::new(),
        }
    }

    /// Create a new assistant with the given configuration.
    pub fn with_config(config: AssistanceConfig) -> Self {
        Self {
            config,
            suggestions: HashMap::new(),
        }
    }

    /// Return a reference to the current configuration.
    pub fn config(&self) -> &AssistanceConfig {
        &self.config
    }

    /// Update the configuration.
    pub fn set_config(&mut self, config: AssistanceConfig) {
        self.config = config;
    }

    /// Evaluate intent predictions and generate suggestions.
    ///
    /// Returns the IDs of newly created suggestions.
    pub fn evaluate_and_suggest(&mut self, predictions: &[IntentPrediction]) -> Vec<Uuid> {
        if !self.config.enable_proactive {
            return Vec::new();
        }

        // Expire old suggestions first
        self.expire_old_suggestions();

        let active_count = self.active_count();
        let capacity = self
            .config
            .max_active_suggestions
            .saturating_sub(active_count);

        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        let mut new_ids = Vec::new();

        for pred in predictions.iter().take(capacity) {
            if pred.confidence < self.config.min_confidence {
                continue;
            }

            let action = pred
                .suggested_action
                .clone()
                .unwrap_or_else(|| format!("Assist with: {}", pred.intent));

            let suggestion = Suggestion {
                id: Uuid::new_v4(),
                intent: pred.intent.clone(),
                action,
                confidence: pred.confidence_level(),
                status: SuggestionStatus::Queued,
                created_at: now,
            };

            new_ids.push(suggestion.id);
            self.suggestions.insert(suggestion.id, suggestion);
        }

        new_ids
    }

    /// Mark a suggestion as accepted by the user.
    pub fn accept_suggestion(&mut self, id: Uuid) -> Result<&Suggestion, OmniscienceError> {
        let suggestion = self
            .suggestions
            .get_mut(&id)
            .ok_or(OmniscienceError::SuggestionNotFound { id: id.to_string() })?;
        suggestion.status = SuggestionStatus::Accepted;
        Ok(suggestion)
    }

    /// Mark a suggestion as dismissed by the user.
    pub fn dismiss_suggestion(&mut self, id: Uuid) -> Result<&Suggestion, OmniscienceError> {
        let suggestion = self
            .suggestions
            .get_mut(&id)
            .ok_or(OmniscienceError::SuggestionNotFound { id: id.to_string() })?;
        suggestion.status = SuggestionStatus::Dismissed;
        Ok(suggestion)
    }

    /// Mark a suggestion as shown to the user.
    pub fn show_suggestion(&mut self, id: Uuid) -> Result<&Suggestion, OmniscienceError> {
        let suggestion = self
            .suggestions
            .get_mut(&id)
            .ok_or(OmniscienceError::SuggestionNotFound { id: id.to_string() })?;
        suggestion.status = SuggestionStatus::Shown;
        Ok(suggestion)
    }

    /// Get a suggestion by ID.
    pub fn get_suggestion(&self, id: &Uuid) -> Option<&Suggestion> {
        self.suggestions.get(id)
    }

    /// Return all suggestions with a given status.
    pub fn suggestions_by_status(&self, status: SuggestionStatus) -> Vec<&Suggestion> {
        self.suggestions
            .values()
            .filter(|s| s.status == status)
            .collect()
    }

    /// Return the number of active (non-terminal) suggestions.
    pub fn active_count(&self) -> usize {
        self.suggestions
            .values()
            .filter(|s| matches!(s.status, SuggestionStatus::Queued | SuggestionStatus::Shown))
            .count()
    }

    /// Return total number of suggestions (all statuses).
    pub fn total_count(&self) -> usize {
        self.suggestions.len()
    }

    /// Expire old suggestions that have passed the expiry window.
    fn expire_old_suggestions(&mut self) {
        let now = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_millis() as u64;

        let expiry = self.config.suggestion_expiry_ms;
        for suggestion in self.suggestions.values_mut() {
            if matches!(
                suggestion.status,
                SuggestionStatus::Queued | SuggestionStatus::Shown
            ) && now.saturating_sub(suggestion.created_at) > expiry
            {
                suggestion.status = SuggestionStatus::Expired;
            }
        }
    }

    /// Clear all suggestions.
    pub fn clear(&mut self) {
        self.suggestions.clear();
    }
}

impl Default for ProactiveAssistant {
    fn default() -> Self {
        Self::new()
    }
}

// ── Tests ───────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_prediction(intent: &str, confidence: f64, action: Option<&str>) -> IntentPrediction {
        IntentPrediction {
            intent: intent.to_string(),
            confidence,
            evidence: vec!["test".into()],
            suggested_action: action.map(String::from),
            timestamp: 1000,
        }
    }

    #[test]
    fn new_assistant_defaults() {
        let asst = ProactiveAssistant::new();
        assert!(asst.config().enable_proactive);
        assert_eq!(asst.total_count(), 0);
    }

    #[test]
    fn evaluate_creates_suggestions() {
        let mut asst = ProactiveAssistant::new();
        let preds = vec![make_prediction("user stuck", 0.8, Some("help them"))];
        let ids = asst.evaluate_and_suggest(&preds);
        assert_eq!(ids.len(), 1);
        assert_eq!(asst.total_count(), 1);

        let suggestion = asst.get_suggestion(&ids[0]).unwrap();
        assert_eq!(suggestion.status, SuggestionStatus::Queued);
        assert_eq!(suggestion.action, "help them");
    }

    #[test]
    fn disabled_assistant_generates_nothing() {
        let config = AssistanceConfig {
            enable_proactive: false,
            ..Default::default()
        };
        let mut asst = ProactiveAssistant::with_config(config);
        let preds = vec![make_prediction("test", 0.9, None)];
        let ids = asst.evaluate_and_suggest(&preds);
        assert!(ids.is_empty());
    }

    #[test]
    fn low_confidence_filtered() {
        let config = AssistanceConfig {
            min_confidence: 0.8,
            ..Default::default()
        };
        let mut asst = ProactiveAssistant::with_config(config);
        let preds = vec![make_prediction("test", 0.5, None)];
        let ids = asst.evaluate_and_suggest(&preds);
        assert!(ids.is_empty());
    }

    #[test]
    fn max_active_respected() {
        let config = AssistanceConfig {
            max_active_suggestions: 2,
            ..Default::default()
        };
        let mut asst = ProactiveAssistant::with_config(config);
        let preds = vec![
            make_prediction("a", 0.9, None),
            make_prediction("b", 0.8, None),
            make_prediction("c", 0.7, None),
        ];
        let ids = asst.evaluate_and_suggest(&preds);
        assert_eq!(ids.len(), 2);
    }

    #[test]
    fn accept_suggestion() {
        let mut asst = ProactiveAssistant::new();
        let preds = vec![make_prediction("test", 0.9, Some("action"))];
        let ids = asst.evaluate_and_suggest(&preds);
        let s = asst.accept_suggestion(ids[0]).unwrap();
        assert_eq!(s.status, SuggestionStatus::Accepted);
    }

    #[test]
    fn dismiss_suggestion() {
        let mut asst = ProactiveAssistant::new();
        let preds = vec![make_prediction("test", 0.9, Some("action"))];
        let ids = asst.evaluate_and_suggest(&preds);
        let s = asst.dismiss_suggestion(ids[0]).unwrap();
        assert_eq!(s.status, SuggestionStatus::Dismissed);
    }

    #[test]
    fn show_suggestion() {
        let mut asst = ProactiveAssistant::new();
        let preds = vec![make_prediction("test", 0.9, Some("action"))];
        let ids = asst.evaluate_and_suggest(&preds);
        let s = asst.show_suggestion(ids[0]).unwrap();
        assert_eq!(s.status, SuggestionStatus::Shown);
    }

    #[test]
    fn not_found_error() {
        let mut asst = ProactiveAssistant::new();
        let result = asst.accept_suggestion(Uuid::new_v4());
        assert!(result.is_err());
    }

    #[test]
    fn suggestions_by_status() {
        let mut asst = ProactiveAssistant::new();
        let preds = vec![
            make_prediction("a", 0.9, None),
            make_prediction("b", 0.8, None),
        ];
        let ids = asst.evaluate_and_suggest(&preds);
        asst.accept_suggestion(ids[0]).unwrap();

        let queued = asst.suggestions_by_status(SuggestionStatus::Queued);
        assert_eq!(queued.len(), 1);
        let accepted = asst.suggestions_by_status(SuggestionStatus::Accepted);
        assert_eq!(accepted.len(), 1);
    }

    #[test]
    fn active_count() {
        let mut asst = ProactiveAssistant::new();
        let preds = vec![
            make_prediction("a", 0.9, None),
            make_prediction("b", 0.8, None),
        ];
        let ids = asst.evaluate_and_suggest(&preds);
        assert_eq!(asst.active_count(), 2);
        asst.dismiss_suggestion(ids[0]).unwrap();
        assert_eq!(asst.active_count(), 1);
    }

    #[test]
    fn clear_suggestions() {
        let mut asst = ProactiveAssistant::new();
        let preds = vec![make_prediction("test", 0.9, None)];
        asst.evaluate_and_suggest(&preds);
        asst.clear();
        assert_eq!(asst.total_count(), 0);
    }

    #[test]
    fn default_action_when_none_provided() {
        let mut asst = ProactiveAssistant::new();
        let preds = vec![make_prediction("user editing code", 0.9, None)];
        let ids = asst.evaluate_and_suggest(&preds);
        let s = asst.get_suggestion(&ids[0]).unwrap();
        assert!(s.action.contains("Assist with"));
    }

    #[test]
    fn suggestion_serialization() {
        let suggestion = Suggestion {
            id: Uuid::new_v4(),
            intent: "test".into(),
            action: "do something".into(),
            confidence: ConfidenceLevel::High,
            status: SuggestionStatus::Queued,
            created_at: 1000,
        };
        let json = serde_json::to_string(&suggestion).unwrap();
        let deser: Suggestion = serde_json::from_str(&json).unwrap();
        assert_eq!(deser.intent, "test");
    }

    #[test]
    fn config_serialization() {
        let config = AssistanceConfig::default();
        let json = serde_json::to_string(&config).unwrap();
        let deser: AssistanceConfig = serde_json::from_str(&json).unwrap();
        assert_eq!(deser.enable_proactive, config.enable_proactive);
    }

    #[test]
    fn notification_style_variants() {
        for style in [
            NotificationStyle::Silent,
            NotificationStyle::Subtle,
            NotificationStyle::Normal,
            NotificationStyle::Prominent,
        ] {
            let json = serde_json::to_string(&style).unwrap();
            let deser: NotificationStyle = serde_json::from_str(&json).unwrap();
            assert_eq!(deser, style);
        }
    }
}
