//! Data provenance and lineage tracking.
//!
//! Provides structured tracking of data origin, transformations, and flow
//! through agents. Hooks into existing audit events to automatically build
//! lineage records.

use crate::audit::{AuditTrail, EventType};
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::HashMap;
use uuid::Uuid;

// ---------------------------------------------------------------------------
// Core types
// ---------------------------------------------------------------------------

/// Where a piece of data originated.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DataOrigin {
    /// Provided directly by a user.
    UserInput,
    /// Generated by an LLM.
    LlmResponse,
    /// Read from the filesystem.
    FileRead,
    /// Received from another agent.
    AgentMessage,
    /// Fetched from an external API or service.
    ExternalApi,
}

impl DataOrigin {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::UserInput => "user_input",
            Self::LlmResponse => "llm_response",
            Self::FileRead => "file_read",
            Self::AgentMessage => "agent_message",
            Self::ExternalApi => "external_api",
        }
    }
}

/// A transformation applied to data during processing.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct Transformation {
    /// What happened to the data.
    pub kind: TransformationKind,
    /// Agent that applied the transformation.
    pub agent_id: Uuid,
    /// Unix timestamp when the transformation occurred.
    pub timestamp: u64,
    /// Optional description of what changed.
    pub description: String,
}

/// The type of transformation applied.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TransformationKind {
    /// PII or sensitive data was redacted.
    Redacted,
    /// Data was summarised or condensed.
    Summarized,
    /// Data was classified or categorised.
    Classified,
    /// Data was delegated to another agent.
    DelegatedToAgent,
    /// Data was sent to an LLM for processing.
    SentToLlm,
    /// Data was written to a file or output.
    WrittenToOutput,
    /// Custom transformation.
    Custom(String),
}

impl TransformationKind {
    pub fn as_str(&self) -> &str {
        match self {
            Self::Redacted => "redacted",
            Self::Summarized => "summarized",
            Self::Classified => "classified",
            Self::DelegatedToAgent => "delegated_to_agent",
            Self::SentToLlm => "sent_to_llm",
            Self::WrittenToOutput => "written_to_output",
            Self::Custom(s) => s,
        }
    }
}

/// Sensitivity classification for tracked data.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DataClassification {
    Public,
    Internal,
    Confidential,
    Restricted,
}

impl DataClassification {
    pub fn as_str(self) -> &'static str {
        match self {
            Self::Public => "public",
            Self::Internal => "internal",
            Self::Confidential => "confidential",
            Self::Restricted => "restricted",
        }
    }
}

/// A single lineage record tracking one piece of data through the system.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct DataLineage {
    /// Unique identifier for this data lineage chain.
    pub data_id: Uuid,
    /// Where the data originated.
    pub origin: DataOrigin,
    /// Ordered list of transformations applied to the data.
    pub transformations: Vec<Transformation>,
    /// The agent currently holding the data.
    pub current_holder: Uuid,
    /// Unix timestamp when the lineage record was created.
    pub created_at: u64,
    /// Sensitivity classification.
    pub classification: DataClassification,
    /// Human-readable label for this data item.
    pub label: String,
}

/// Summary of all data an agent has touched.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AgentLineageReport {
    /// Agent this report is for.
    pub agent_id: Uuid,
    /// All lineage records where this agent is involved.
    pub lineage_entries: Vec<DataLineage>,
    /// Count of data items originated by this agent.
    pub originated: usize,
    /// Count of data items received via delegation.
    pub received: usize,
    /// Count of transformations applied by this agent.
    pub transformations_applied: usize,
    /// Unix timestamp when the report was generated.
    pub generated_at: u64,
}

// ---------------------------------------------------------------------------
// ProvenanceTracker
// ---------------------------------------------------------------------------

/// Tracks data provenance by building lineage records from audit events
/// and explicit registration calls.
#[derive(Debug, Clone, Default)]
pub struct ProvenanceTracker {
    lineage: HashMap<Uuid, DataLineage>,
}

impl ProvenanceTracker {
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a new data lineage entry (e.g. when an agent reads a file).
    pub fn record_origin(
        &mut self,
        origin: DataOrigin,
        agent_id: Uuid,
        classification: DataClassification,
        label: &str,
        audit_trail: &mut AuditTrail,
    ) -> Uuid {
        let data_id = Uuid::new_v4();
        let now = current_timestamp();

        let lineage = DataLineage {
            data_id,
            origin: origin.clone(),
            transformations: Vec::new(),
            current_holder: agent_id,
            created_at: now,
            classification,
            label: label.to_string(),
        };

        self.lineage.insert(data_id, lineage);

        // Audit the origin event
        let _ = audit_trail.append_event(
            agent_id,
            EventType::StateChange,
            json!({
                "event": "provenance.origin",
                "data_id": data_id.to_string(),
                "origin": origin.as_str(),
                "classification": classification.as_str(),
                "label": label,
            }),
        );

        data_id
    }

    /// Record a transformation on tracked data.
    pub fn record_transformation(
        &mut self,
        data_id: Uuid,
        kind: TransformationKind,
        agent_id: Uuid,
        description: &str,
        audit_trail: &mut AuditTrail,
    ) -> bool {
        let now = current_timestamp();

        let Some(lineage) = self.lineage.get_mut(&data_id) else {
            return false;
        };

        let transformation = Transformation {
            kind: kind.clone(),
            agent_id,
            timestamp: now,
            description: description.to_string(),
        };

        lineage.transformations.push(transformation);

        let _ = audit_trail.append_event(
            agent_id,
            EventType::StateChange,
            json!({
                "event": "provenance.transformation",
                "data_id": data_id.to_string(),
                "kind": kind.as_str(),
                "description": description,
            }),
        );

        true
    }

    /// Record a delegation handoff — data moves from one agent to another.
    pub fn record_delegation(
        &mut self,
        data_id: Uuid,
        from_agent: Uuid,
        to_agent: Uuid,
        reason: &str,
        audit_trail: &mut AuditTrail,
    ) -> bool {
        let now = current_timestamp();

        let Some(lineage) = self.lineage.get_mut(&data_id) else {
            return false;
        };

        lineage.transformations.push(Transformation {
            kind: TransformationKind::DelegatedToAgent,
            agent_id: from_agent,
            timestamp: now,
            description: format!("Delegated to agent {} — {}", to_agent, reason),
        });
        lineage.current_holder = to_agent;

        let _ = audit_trail.append_event(
            from_agent,
            EventType::StateChange,
            json!({
                "event": "provenance.delegation",
                "data_id": data_id.to_string(),
                "from_agent": from_agent.to_string(),
                "to_agent": to_agent.to_string(),
                "reason": reason,
            }),
        );

        true
    }

    /// Record that PII redaction was applied to tracked data.
    pub fn record_redaction(
        &mut self,
        data_id: Uuid,
        agent_id: Uuid,
        description: &str,
        audit_trail: &mut AuditTrail,
    ) -> bool {
        self.record_transformation(
            data_id,
            TransformationKind::Redacted,
            agent_id,
            description,
            audit_trail,
        )
    }

    /// Query the full lineage chain for a data item.
    pub fn query_lineage(&self, data_id: &Uuid) -> Option<&DataLineage> {
        self.lineage.get(data_id)
    }

    /// Export a lineage report for an agent — all data the agent has touched.
    pub fn export_lineage_report(&self, agent_id: Uuid) -> AgentLineageReport {
        let now = current_timestamp();
        let mut entries = Vec::new();
        let mut originated = 0usize;
        let mut received = 0usize;
        let mut transformations_applied = 0usize;

        let agent_id_str = agent_id.to_string();

        for lineage in self.lineage.values() {
            // Check if agent ever held or transformed this data
            let agent_involved = lineage.current_holder == agent_id
                || lineage
                    .transformations
                    .iter()
                    .any(|t| t.agent_id == agent_id);

            // Check if data was delegated TO this agent (description contains agent UUID)
            let was_delegated_to = lineage.transformations.iter().any(|t| {
                t.kind == TransformationKind::DelegatedToAgent
                    && t.description.contains(&agent_id_str)
            });

            if !agent_involved && !was_delegated_to {
                continue;
            }

            entries.push(lineage.clone());

            // The agent originated this data if no transformations exist
            // and it's the current holder, or the first transformation is by this agent
            // with no prior delegation
            let is_originator =
                lineage.transformations.is_empty() && lineage.current_holder == agent_id;
            if is_originator {
                originated += 1;
            }

            if was_delegated_to {
                received += 1;
            }

            transformations_applied += lineage
                .transformations
                .iter()
                .filter(|t| t.agent_id == agent_id)
                .count();
        }

        AgentLineageReport {
            agent_id,
            lineage_entries: entries,
            originated,
            received,
            transformations_applied,
            generated_at: now,
        }
    }

    /// Build lineage entries from existing audit trail events.
    ///
    /// Scans the audit trail for provenance-related events and reconstructs
    /// lineage records. Useful when replaying or importing audit history.
    pub fn rebuild_from_audit(&mut self, audit_trail: &AuditTrail) {
        for event in audit_trail.events() {
            let Some(obj) = event.payload.as_object() else {
                continue;
            };
            let Some(event_name) = obj.get("event").and_then(|v| v.as_str()) else {
                continue;
            };

            match event_name {
                "provenance.origin" => {
                    if let (Some(data_id_str), Some(origin_str), Some(label)) = (
                        obj.get("data_id").and_then(|v| v.as_str()),
                        obj.get("origin").and_then(|v| v.as_str()),
                        obj.get("label").and_then(|v| v.as_str()),
                    ) {
                        if let Ok(data_id) = Uuid::parse_str(data_id_str) {
                            let origin = match origin_str {
                                "user_input" => DataOrigin::UserInput,
                                "llm_response" => DataOrigin::LlmResponse,
                                "file_read" => DataOrigin::FileRead,
                                "agent_message" => DataOrigin::AgentMessage,
                                "external_api" => DataOrigin::ExternalApi,
                                _ => continue,
                            };
                            let classification = match obj
                                .get("classification")
                                .and_then(|v| v.as_str())
                                .unwrap_or("internal")
                            {
                                "public" => DataClassification::Public,
                                "confidential" => DataClassification::Confidential,
                                "restricted" => DataClassification::Restricted,
                                _ => DataClassification::Internal,
                            };
                            self.lineage.insert(
                                data_id,
                                DataLineage {
                                    data_id,
                                    origin,
                                    transformations: Vec::new(),
                                    current_holder: event.agent_id,
                                    created_at: event.timestamp,
                                    classification,
                                    label: label.to_string(),
                                },
                            );
                        }
                    }
                }
                "provenance.transformation" => {
                    if let (Some(data_id_str), Some(kind_str)) = (
                        obj.get("data_id").and_then(|v| v.as_str()),
                        obj.get("kind").and_then(|v| v.as_str()),
                    ) {
                        if let Ok(data_id) = Uuid::parse_str(data_id_str) {
                            if let Some(lineage) = self.lineage.get_mut(&data_id) {
                                let kind = match kind_str {
                                    "redacted" => TransformationKind::Redacted,
                                    "summarized" => TransformationKind::Summarized,
                                    "classified" => TransformationKind::Classified,
                                    "sent_to_llm" => TransformationKind::SentToLlm,
                                    "written_to_output" => TransformationKind::WrittenToOutput,
                                    "delegated_to_agent" => TransformationKind::DelegatedToAgent,
                                    other => TransformationKind::Custom(other.to_string()),
                                };
                                let description = obj
                                    .get("description")
                                    .and_then(|v| v.as_str())
                                    .unwrap_or("")
                                    .to_string();
                                lineage.transformations.push(Transformation {
                                    kind,
                                    agent_id: event.agent_id,
                                    timestamp: event.timestamp,
                                    description,
                                });
                            }
                        }
                    }
                }
                "provenance.delegation" => {
                    if let (Some(data_id_str), Some(to_agent_str)) = (
                        obj.get("data_id").and_then(|v| v.as_str()),
                        obj.get("to_agent").and_then(|v| v.as_str()),
                    ) {
                        if let (Ok(data_id), Ok(to_agent)) =
                            (Uuid::parse_str(data_id_str), Uuid::parse_str(to_agent_str))
                        {
                            if let Some(lineage) = self.lineage.get_mut(&data_id) {
                                let reason = obj
                                    .get("reason")
                                    .and_then(|v| v.as_str())
                                    .unwrap_or("")
                                    .to_string();
                                lineage.transformations.push(Transformation {
                                    kind: TransformationKind::DelegatedToAgent,
                                    agent_id: event.agent_id,
                                    timestamp: event.timestamp,
                                    description: format!(
                                        "Delegated to agent {} — {}",
                                        to_agent, reason
                                    ),
                                });
                                lineage.current_holder = to_agent;
                            }
                        }
                    }
                }
                _ => {}
            }
        }
    }

    /// Number of lineage entries currently tracked.
    pub fn entry_count(&self) -> usize {
        self.lineage.len()
    }
}

fn current_timestamp() -> u64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::audit::AuditTrail;

    #[test]
    fn lineage_tracks_file_read_to_llm_to_output() {
        let agent_id = Uuid::new_v4();
        let mut trail = AuditTrail::new();
        let mut tracker = ProvenanceTracker::new();

        // 1. Agent reads a file
        let data_id = tracker.record_origin(
            DataOrigin::FileRead,
            agent_id,
            DataClassification::Internal,
            "config.toml",
            &mut trail,
        );

        // 2. Agent sends data to LLM
        assert!(tracker.record_transformation(
            data_id,
            TransformationKind::SentToLlm,
            agent_id,
            "Sent config to claude-sonnet for analysis",
            &mut trail,
        ));

        // 3. Agent writes output
        assert!(tracker.record_transformation(
            data_id,
            TransformationKind::WrittenToOutput,
            agent_id,
            "Analysis results written to report.md",
            &mut trail,
        ));

        // Verify full chain
        let lineage = tracker.query_lineage(&data_id).expect("lineage must exist");
        assert_eq!(lineage.origin, DataOrigin::FileRead);
        assert_eq!(lineage.label, "config.toml");
        assert_eq!(lineage.classification, DataClassification::Internal);
        assert_eq!(lineage.transformations.len(), 2);
        assert_eq!(
            lineage.transformations[0].kind,
            TransformationKind::SentToLlm
        );
        assert_eq!(
            lineage.transformations[1].kind,
            TransformationKind::WrittenToOutput
        );
        assert_eq!(lineage.current_holder, agent_id);
    }

    #[test]
    fn delegation_handoff_recorded() {
        let agent_a = Uuid::new_v4();
        let agent_b = Uuid::new_v4();
        let mut trail = AuditTrail::new();
        let mut tracker = ProvenanceTracker::new();

        // Agent A reads user input
        let data_id = tracker.record_origin(
            DataOrigin::UserInput,
            agent_a,
            DataClassification::Confidential,
            "user query",
            &mut trail,
        );

        // Agent A delegates to Agent B
        assert!(tracker.record_delegation(
            data_id,
            agent_a,
            agent_b,
            "specialist processing needed",
            &mut trail,
        ));

        let lineage = tracker.query_lineage(&data_id).unwrap();
        assert_eq!(lineage.current_holder, agent_b);
        assert_eq!(lineage.transformations.len(), 1);
        assert_eq!(
            lineage.transformations[0].kind,
            TransformationKind::DelegatedToAgent
        );
        assert!(lineage.transformations[0]
            .description
            .contains(&agent_b.to_string()));
        assert_eq!(lineage.transformations[0].agent_id, agent_a);
    }

    #[test]
    fn redaction_transformation_logged() {
        let agent_id = Uuid::new_v4();
        let mut trail = AuditTrail::new();
        let mut tracker = ProvenanceTracker::new();

        let data_id = tracker.record_origin(
            DataOrigin::UserInput,
            agent_id,
            DataClassification::Restricted,
            "PII-containing document",
            &mut trail,
        );

        assert!(tracker.record_redaction(
            data_id,
            agent_id,
            "Email and phone numbers redacted",
            &mut trail,
        ));

        let lineage = tracker.query_lineage(&data_id).unwrap();
        assert_eq!(lineage.classification, DataClassification::Restricted);
        assert_eq!(lineage.transformations.len(), 1);
        assert_eq!(
            lineage.transformations[0].kind,
            TransformationKind::Redacted
        );
        assert!(lineage.transformations[0]
            .description
            .contains("Email and phone"));
    }

    #[test]
    fn lineage_query_returns_full_chain() {
        let agent_id = Uuid::new_v4();
        let other_agent = Uuid::new_v4();
        let mut trail = AuditTrail::new();
        let mut tracker = ProvenanceTracker::new();

        // Build a complex chain
        let data_id = tracker.record_origin(
            DataOrigin::ExternalApi,
            agent_id,
            DataClassification::Internal,
            "API response from weather service",
            &mut trail,
        );

        tracker.record_transformation(
            data_id,
            TransformationKind::Classified,
            agent_id,
            "Classified as weather data",
            &mut trail,
        );

        tracker.record_transformation(
            data_id,
            TransformationKind::Summarized,
            agent_id,
            "Extracted key metrics",
            &mut trail,
        );

        tracker.record_redaction(
            data_id,
            agent_id,
            "Removed API key from response",
            &mut trail,
        );

        tracker.record_delegation(
            data_id,
            agent_id,
            other_agent,
            "forward to reporting agent",
            &mut trail,
        );

        tracker.record_transformation(
            data_id,
            TransformationKind::SentToLlm,
            other_agent,
            "Sent to LLM for report generation",
            &mut trail,
        );

        // Query and verify full chain
        let lineage = tracker.query_lineage(&data_id).unwrap();
        assert_eq!(lineage.origin, DataOrigin::ExternalApi);
        assert_eq!(lineage.transformations.len(), 5);
        assert_eq!(
            lineage.transformations[0].kind,
            TransformationKind::Classified
        );
        assert_eq!(
            lineage.transformations[1].kind,
            TransformationKind::Summarized
        );
        assert_eq!(
            lineage.transformations[2].kind,
            TransformationKind::Redacted
        );
        assert_eq!(
            lineage.transformations[3].kind,
            TransformationKind::DelegatedToAgent
        );
        assert_eq!(
            lineage.transformations[4].kind,
            TransformationKind::SentToLlm
        );

        // Current holder is the delegated-to agent
        assert_eq!(lineage.current_holder, other_agent);

        // Last transformation was by other_agent
        assert_eq!(lineage.transformations[4].agent_id, other_agent);
    }

    #[test]
    fn transformation_on_unknown_data_returns_false() {
        let agent_id = Uuid::new_v4();
        let mut trail = AuditTrail::new();
        let mut tracker = ProvenanceTracker::new();

        let unknown_id = Uuid::new_v4();
        assert!(!tracker.record_transformation(
            unknown_id,
            TransformationKind::Summarized,
            agent_id,
            "this should fail",
            &mut trail,
        ));
    }

    #[test]
    fn export_lineage_report_for_agent() {
        let agent_a = Uuid::new_v4();
        let agent_b = Uuid::new_v4();
        let mut trail = AuditTrail::new();
        let mut tracker = ProvenanceTracker::new();

        // Agent A creates two data items
        let d1 = tracker.record_origin(
            DataOrigin::FileRead,
            agent_a,
            DataClassification::Internal,
            "file1.txt",
            &mut trail,
        );
        let d2 = tracker.record_origin(
            DataOrigin::UserInput,
            agent_a,
            DataClassification::Public,
            "user query",
            &mut trail,
        );

        // Agent A transforms d1
        tracker.record_transformation(
            d1,
            TransformationKind::SentToLlm,
            agent_a,
            "sent to LLM",
            &mut trail,
        );

        // Agent B creates its own data (agent A should not see this)
        tracker.record_origin(
            DataOrigin::FileRead,
            agent_b,
            DataClassification::Internal,
            "agent_b_file.txt",
            &mut trail,
        );

        // Delegate d2 to agent B
        tracker.record_delegation(d2, agent_a, agent_b, "handoff", &mut trail);

        let report = tracker.export_lineage_report(agent_a);
        assert_eq!(report.agent_id, agent_a);
        // Agent A originated d1, was involved in d2 (delegated away)
        assert!(report.lineage_entries.len() >= 2);
        assert!(report.transformations_applied > 0);
    }

    #[test]
    fn rebuild_from_audit_trail() {
        let agent_id = Uuid::new_v4();
        let mut trail = AuditTrail::new();
        let mut tracker = ProvenanceTracker::new();

        // Record some lineage
        let data_id = tracker.record_origin(
            DataOrigin::FileRead,
            agent_id,
            DataClassification::Internal,
            "test.txt",
            &mut trail,
        );
        tracker.record_transformation(
            data_id,
            TransformationKind::SentToLlm,
            agent_id,
            "analysis",
            &mut trail,
        );
        tracker.record_redaction(data_id, agent_id, "PII removed", &mut trail);

        // Build a new tracker from the audit trail
        let mut rebuilt = ProvenanceTracker::new();
        rebuilt.rebuild_from_audit(&trail);

        let lineage = rebuilt.query_lineage(&data_id).expect("should be rebuilt");
        assert_eq!(lineage.origin, DataOrigin::FileRead);
        assert_eq!(lineage.label, "test.txt");
        assert_eq!(lineage.transformations.len(), 2);
        assert_eq!(
            lineage.transformations[0].kind,
            TransformationKind::SentToLlm
        );
        assert_eq!(
            lineage.transformations[1].kind,
            TransformationKind::Redacted
        );
    }

    #[test]
    fn audit_events_emitted_for_provenance_operations() {
        let agent_id = Uuid::new_v4();
        let mut trail = AuditTrail::new();
        let mut tracker = ProvenanceTracker::new();

        let data_id = tracker.record_origin(
            DataOrigin::FileRead,
            agent_id,
            DataClassification::Internal,
            "test.txt",
            &mut trail,
        );
        tracker.record_transformation(
            data_id,
            TransformationKind::SentToLlm,
            agent_id,
            "LLM analysis",
            &mut trail,
        );

        let events = trail.events();
        assert!(events.len() >= 2);

        let origin_event = events
            .iter()
            .find(|e| {
                e.payload
                    .get("event")
                    .and_then(|v| v.as_str())
                    .is_some_and(|s| s == "provenance.origin")
            })
            .expect("origin audit event");
        assert_eq!(origin_event.payload["data_id"], data_id.to_string());

        let transform_event = events
            .iter()
            .find(|e| {
                e.payload
                    .get("event")
                    .and_then(|v| v.as_str())
                    .is_some_and(|s| s == "provenance.transformation")
            })
            .expect("transformation audit event");
        assert_eq!(transform_event.payload["kind"], "sent_to_llm");
    }

    #[test]
    fn entry_count_tracks_lineage_items() {
        let agent_id = Uuid::new_v4();
        let mut trail = AuditTrail::new();
        let mut tracker = ProvenanceTracker::new();

        assert_eq!(tracker.entry_count(), 0);

        tracker.record_origin(
            DataOrigin::UserInput,
            agent_id,
            DataClassification::Public,
            "item1",
            &mut trail,
        );
        assert_eq!(tracker.entry_count(), 1);

        tracker.record_origin(
            DataOrigin::FileRead,
            agent_id,
            DataClassification::Internal,
            "item2",
            &mut trail,
        );
        assert_eq!(tracker.entry_count(), 2);
    }
}
