apiVersion: v1
kind: Service
metadata:
  name: {{ include "nexus-os.fullname" . }}
  labels:
    {{- include "nexus-os.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.server.port }}
      targetPort: http
      name: http
    - port: {{ .Values.server.mcpPort }}
      targetPort: mcp
      name: mcp
    - port: {{ .Values.server.a2aPort }}
      targetPort: a2a
      name: a2a
  selector:
    {{- include "nexus-os.selectorLabels" . | nindent 4 }}
