#!/usr/bin/env python3
"""P2-V1-R3B-I4-R1 old -> new mapping of the accepted I4 controls and
guards, generated from the candidate runs: for each of the 21 I4
behavioural controls and the 19 I4 API/type guards, its I4 definition's
test, its I4-R1 test, whether it is unchanged or adapted (and why), and its
I4-R1 result.

Usage: mapping.py <candidate runs directory> <output .md>
"""
import json
import pathlib
import sys


def main():
    runs, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    controls = json.loads((runs / "controls/scope/summary.json").read_text())["counted"]
    guards = json.loads((runs / "controls/api-guards/summary.json").read_text())["guards"]
    lines = ["# P2-V1-R3B-I4-R1: the accepted I4 controls and guards, old -> new", "",
             "Generated by `scripts/mapping.py` from the candidate runs. \"Unchanged\": the I4 "
             "definition runs as it is (the behavioural controls import it from the I4 evidence's "
             "own runner, verified by SHA-256). \"Adapted\": the repaired shape moved the same "
             "defect point; the same mutation, test and marker (controls) or the same probe "
             "intention (guards), with the reason.", "",
             "## Behavioural controls (21: 16 required, 5 additional in I4)", "",
             "| Control | I4 category | I4 test | I4-R1 test | Mapping | Reason | I4-R1 result |",
             "|---|---|---|---|---|---|---|"]
    ok = True
    i4c = [c for c in controls if c["category"].startswith("i4-")]
    for c in i4c:
        m = c["mapping"] or {}
        same_test = m.get("i4_test") == c["test"]
        ok &= c["ok"] and same_test
        lines.append(f"| `{c['id']}` | {c['category'][3:]} | `{m.get('i4_test')}` | "
                     f"{'same' if same_test else '`' + c['test'] + '`'} | {m.get('kind')} | "
                     f"{m.get('reason')} | {'ok' if c['ok'] else 'NOT OK'} |")
    lines += ["", "## API/type guards (19 in I4)", "",
              "| Guard | Kind | Mapping | I4-R1 expected errors | I4-R1 result |", "|---|---|---|---|---|"]
    i4g = [g for g in guards if g.get("family") == "i4"]
    for g in i4g:
        ok &= g["ok"]
        errors = "<br>".join(f"`{e}`" for e in g["expected"])
        lines.append(f"| `{g['id']}` | {g['kind']} | {g['mapping']} | {errors} | "
                     f"{'ok' if g['ok'] else 'NOT OK'} |")
    lines += ["", f"Behavioural controls mapped: {len(i4c)} "
              f"({sum(1 for c in i4c if (c['mapping'] or {}).get('kind') == 'unchanged')} unchanged, "
              f"{sum(1 for c in i4c if (c['mapping'] or {}).get('kind') == 'adapted')} adapted); "
              f"API/type guards mapped: {len(i4g)}.",
              f"RESULT: {'PASS' if ok and len(i4c) == 21 and len(i4g) == 19 else 'FAIL'}"]
    out.write_text("\n".join(lines) + "\n")
    print(lines[-1])
    return 0 if lines[-1].endswith("PASS") else 1


if __name__ == "__main__":
    sys.exit(main())
