//! Consciousness engine — manages agent states and user behaviour.
//!
//! This is the central integration point that the Tauri layer and
//! chat pipeline interact with.

use super::empathy::{UserBehaviorState, UserInputEvent};
use super::modifiers::{ConsciousnessModifier, LlmModification};
use super::state::{ConsciousnessState, StateSnapshot};
use std::collections::HashMap;

/// Central engine managing consciousness states for all agents and the user.
#[derive(Debug, Clone)]
pub struct ConsciousnessEngine {
    agents: HashMap<String, ConsciousnessState>,
    user_behavior: UserBehaviorState,
}

impl Default for ConsciousnessEngine {
    fn default() -> Self {
        Self::new()
    }
}

impl ConsciousnessEngine {
    pub fn new() -> Self {
        Self {
            agents: HashMap::new(),
            user_behavior: UserBehaviorState::new(),
        }
    }

    // ── Agent consciousness ──────────────────────────────────────

    /// Get or create the consciousness state for an agent.
    pub fn get_agent_state(&mut self, agent_id: &str) -> &ConsciousnessState {
        self.agents
            .entry(agent_id.to_string())
            .or_insert_with(|| ConsciousnessState::new(agent_id))
    }

    /// Get a clone of the agent's consciousness state (for serialization).
    pub fn get_agent_state_snapshot(&mut self, agent_id: &str) -> ConsciousnessState {
        self.get_agent_state(agent_id).clone()
    }

    /// Record a task success for an agent.
    pub fn on_agent_task_success(&mut self, agent_id: &str) {
        let state = self
            .agents
            .entry(agent_id.to_string())
            .or_insert_with(|| ConsciousnessState::new(agent_id));
        state.on_task_success();
    }

    /// Record a task failure for an agent.
    pub fn on_agent_task_failure(&mut self, agent_id: &str, error: &str) {
        let state = self
            .agents
            .entry(agent_id.to_string())
            .or_insert_with(|| ConsciousnessState::new(agent_id));
        state.on_task_failure(error);
    }

    /// Record tokens generated by an agent.
    pub fn on_agent_tokens(&mut self, agent_id: &str, count: u64) {
        let state = self
            .agents
            .entry(agent_id.to_string())
            .or_insert_with(|| ConsciousnessState::new(agent_id));
        state.on_token_generated(count);
    }

    /// Assign a new task to an agent.
    pub fn on_agent_new_task(&mut self, agent_id: &str, description: &str, complexity: f64) {
        let state = self
            .agents
            .entry(agent_id.to_string())
            .or_insert_with(|| ConsciousnessState::new(agent_id));
        state.on_new_task(description, complexity);
    }

    /// Idle-tick all agents (call periodically for recovery).
    pub fn tick_all_idle(&mut self) {
        for state in self.agents.values_mut() {
            state.on_idle_tick();
        }
    }

    /// Get the LLM modification for a given agent.
    pub fn get_llm_modification(&mut self, agent_id: &str) -> LlmModification {
        let state = self.get_agent_state(agent_id);
        ConsciousnessModifier::apply(state)
    }

    /// Get emotional history for an agent.
    pub fn get_agent_history(&mut self, agent_id: &str, limit: u32) -> Vec<StateSnapshot> {
        let state = self.get_agent_state(agent_id);
        let history = &state.emotional_history;
        let start = if (limit as usize) < history.len() {
            history.len() - limit as usize
        } else {
            0
        };
        history[start..].to_vec()
    }

    /// Reset an agent's consciousness (after break / manual reset).
    pub fn reset_agent(&mut self, agent_id: &str) {
        if let Some(state) = self.agents.get_mut(agent_id) {
            state.reset();
        }
    }

    // ── User behaviour ───────────────────────────────────────────

    /// Process a user input event.
    pub fn report_user_event(&mut self, event: &UserInputEvent) {
        self.user_behavior.update(event);
    }

    /// Get the current user behaviour state.
    pub fn get_user_behavior(&self) -> &UserBehaviorState {
        &self.user_behavior
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn engine_creates_agent_on_demand() {
        let mut engine = ConsciousnessEngine::new();
        let state = engine.get_agent_state_snapshot("nexus-forge");
        assert_eq!(state.agent_id, "nexus-forge");
        assert!((state.confidence - 0.5).abs() < f64::EPSILON);
    }

    #[test]
    fn engine_tracks_success_failure() {
        let mut engine = ConsciousnessEngine::new();
        engine.on_agent_task_success("a");
        let s = engine.get_agent_state_snapshot("a");
        assert!(s.confidence > 0.5);

        engine.on_agent_task_failure("a", "boom");
        let s2 = engine.get_agent_state_snapshot("a");
        assert!(s2.frustration > 0.0);
    }

    #[test]
    fn engine_llm_modification() {
        let mut engine = ConsciousnessEngine::new();
        let m = engine.get_llm_modification("x");
        // Default state — temperature mid-range
        assert!(m.temperature > 0.5 && m.temperature < 0.8);
    }

    #[test]
    fn engine_history_limit() {
        let mut engine = ConsciousnessEngine::new();
        for _ in 0..20 {
            engine.on_agent_task_success("a");
        }
        let history = engine.get_agent_history("a", 5);
        assert_eq!(history.len(), 5);
    }

    #[test]
    fn engine_reset() {
        let mut engine = ConsciousnessEngine::new();
        engine.on_agent_task_failure("a", "err");
        engine.on_agent_task_failure("a", "err");
        engine.reset_agent("a");
        let s = engine.get_agent_state_snapshot("a");
        assert!((s.frustration - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    fn engine_user_behavior() {
        let mut engine = ConsciousnessEngine::new();
        engine.report_user_event(&UserInputEvent::Keystroke {
            timestamp: 100,
            is_deletion: false,
        });
        // typing_speed_wpm should be non-zero after a keystroke
        assert!(engine.get_user_behavior().typing_speed_wpm >= 0.0);
    }
}
