//! State transition engine — events that change agent consciousness.

use super::state::{now_secs, ConsciousnessState};

/// Consecutive-error threshold that triggers a handoff recommendation.
const HANDOFF_ERROR_THRESHOLD: u32 = 3;
/// Token budget at which fatigue maxes out.
const FATIGUE_TOKEN_CEILING: f64 = 50_000.0;

impl ConsciousnessState {
    /// Agent successfully completed a task.
    pub fn on_task_success(&mut self) {
        self.confidence = (self.confidence + 0.1).min(1.0);
        self.frustration = (self.frustration - 0.2).max(0.0);
        self.fatigue += 0.05; // success still costs energy
        self.task_context.tasks_completed_session += 1;
        self.task_context.errors_this_task = 0;
        self.task_context.last_success = Some(now_secs());
        self.update_derived_states();
        self.push_snapshot("task_success");
    }

    /// Agent failed a task.
    pub fn on_task_failure(&mut self, _error: &str) {
        self.confidence = (self.confidence - 0.15).max(0.0);
        self.frustration = (self.frustration + 0.2).min(1.0);
        self.fatigue += 0.1; // failure costs more energy
        self.task_context.errors_this_task += 1;
        self.task_context.last_failure = Some(now_secs());

        if self.task_context.errors_this_task >= HANDOFF_ERROR_THRESHOLD {
            self.needs_handoff = true;
        }
        self.update_derived_states();
        self.push_snapshot("task_failure");
    }

    /// Tokens were generated by the agent.
    pub fn on_token_generated(&mut self, count: u64) {
        self.task_context.tokens_generated_session += count;
        self.fatigue =
            (self.task_context.tokens_generated_session as f64 / FATIGUE_TOKEN_CEILING).min(1.0);
        self.update_derived_states();
        self.push_snapshot("token_generated");
    }

    /// Idle tick — agent is resting.
    pub fn on_idle_tick(&mut self) {
        self.fatigue = (self.fatigue - 0.01).max(0.0);
        self.frustration = (self.frustration - 0.005).max(0.0);
        self.curiosity = (self.curiosity + 0.02).min(1.0);
        self.update_derived_states();
        self.push_snapshot("idle_tick");
    }

    /// A new task has been assigned to the agent.
    pub fn on_new_task(&mut self, task_description: &str, task_complexity: f64) {
        self.urgency = task_complexity;
        self.focus = 0.8;
        self.task_context.errors_this_task = 0;
        self.task_context.current_task = Some(task_description.to_string());
        self.update_derived_states();
        self.push_snapshot("new_task");
    }

    /// Reset fatigue and frustration (e.g. after a break or manual reset).
    pub fn reset(&mut self) {
        self.fatigue = 0.0;
        self.frustration = 0.0;
        self.confidence = 0.5;
        self.curiosity = 0.5;
        self.urgency = 0.0;
        self.focus = 0.5;
        self.task_context.errors_this_task = 0;
        self.task_context.tokens_generated_session = 0;
        self.update_derived_states();
        self.push_snapshot("manual_reset");
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn success_increases_confidence() {
        let mut s = ConsciousnessState::new("a");
        let before = s.confidence;
        s.on_task_success();
        assert!(s.confidence > before);
        assert_eq!(s.task_context.tasks_completed_session, 1);
    }

    #[test]
    fn failure_increases_frustration() {
        let mut s = ConsciousnessState::new("a");
        s.on_task_failure("oops");
        assert!(s.frustration > 0.0);
        assert!(s.confidence < 0.5);
    }

    #[test]
    fn three_failures_trigger_handoff() {
        let mut s = ConsciousnessState::new("a");
        s.on_task_failure("err1");
        s.on_task_failure("err2");
        s.on_task_failure("err3");
        assert!(s.needs_handoff || s.task_context.errors_this_task >= 3);
    }

    #[test]
    fn token_generation_increases_fatigue() {
        let mut s = ConsciousnessState::new("a");
        s.on_token_generated(25_000);
        assert!((s.fatigue - 0.5).abs() < f64::EPSILON);
        s.on_token_generated(25_000);
        assert!((s.fatigue - 1.0).abs() < f64::EPSILON);
    }

    #[test]
    fn idle_tick_recovers() {
        let mut s = ConsciousnessState::new("a");
        s.fatigue = 0.5;
        s.frustration = 0.5;
        for _ in 0..10 {
            s.on_idle_tick();
        }
        assert!(s.fatigue < 0.5);
        assert!(s.frustration < 0.5);
    }

    #[test]
    fn reset_clears_state() {
        let mut s = ConsciousnessState::new("a");
        s.fatigue = 0.9;
        s.frustration = 0.8;
        s.reset();
        assert!((s.fatigue - 0.0).abs() < f64::EPSILON);
        assert!((s.frustration - 0.0).abs() < f64::EPSILON);
    }

    #[test]
    fn new_task_resets_errors() {
        let mut s = ConsciousnessState::new("a");
        s.on_task_failure("e1");
        s.on_task_failure("e2");
        assert_eq!(s.task_context.errors_this_task, 2);
        s.on_new_task("fresh task", 0.5);
        assert_eq!(s.task_context.errors_this_task, 0);
        assert_eq!(s.task_context.current_task.as_deref(), Some("fresh task"));
    }
}
