#!/usr/bin/env python3
"""P2-V1-R3B-I4 restoration summary: for every mutating suite of the
candidate runs, whether the checkout's files were restored byte for byte
(SHA-256 before and after) and its status kept, from the suites' own
records.

Usage: restoration.py <candidate runs directory> <output .md>
"""
import json
import pathlib
import re
import sys


def main():
    runs, out = pathlib.Path(sys.argv[1]), pathlib.Path(sys.argv[2])
    lines = ["# P2-V1-R3B-I4 restoration summary", "",
             "Generated by `scripts/restoration.py` from the candidate runs. Each mutating suite "
             "hashes the files it may mutate before it starts and after every restoration, and "
             "checks the checkout's Git status.", ""]
    ok = True
    for name, path, key in [
        ("behavioural controls (scope_controls.py)", "controls/scope/summary.json", "summary"),
        ("R3 store controls rerun (R3's runner, unchanged)", "controls/r3-store/summary.json", "summary"),
        ("I2-R1 rerun (I3-I1's runner, unchanged)", "controls/i2r1-rerun/summary.json", "summary"),
    ]:
        summary = json.loads((runs / path).read_text())[key]
        identical = summary.get("identical")
        ok &= identical is True
        lines += [f"## {name}", "", f"- files identical after the suite: {identical}",
                  f"- status after: {summary.get('status')} (expected {summary.get('expected_status')})",
                  "", "| File | SHA-256 before | after |", "|---|---|---|"]
        for file, digest in sorted(summary["original"].items()):
            after = summary["final"].get(file)
            ok &= after == digest
            lines.append(f"| `{file}` | `{digest}` | {'same' if after == digest else '`' + str(after) + '`'} |")
        lines.append("")
    guards = json.loads((runs / "controls/api-guards/summary.json").read_text())["summary"]
    ok &= guards["identical"] and guards["status_restored"]
    lines += ["## API/type guards (api_guards.py)", "",
              f"- sources identical after every reopen: {guards['identical']}",
              f"- status restored (probe file removed): {guards['status_restored']}", ""]
    runs_txt = (runs / "runs.txt").read_text()
    counts = re.findall(r"^(before|after \S+) status entries: (\d+)$", runs_txt, re.M)
    ok &= all(n == "0" for _, n in counts)
    lines += ["## The checkout's status around every step (runs.txt)", ""]
    lines += [f"- {when}: {n} entries" for when, n in counts]
    lines += ["", f"RESULT: {'PASS' if ok else 'FAIL'}"]
    out.write_text("\n".join(lines) + "\n")
    print(lines[-1])
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
